# Generated by generate_emit_runner.mjs. DO NOT EDIT.
import os
import sys
sys.path.insert(0, os.path.dirname(__file__))

from test_models import run_models
from test_nested import run_nested
from test_nested_deep import run_nested_deep

passed = 0
failed = 0
p, f = run_models(); passed += p; failed += f
p, f = run_nested(); passed += p; failed += f
p, f = run_nested_deep(); passed += p; failed += f

print(f"emit-python: {passed} passed, {failed} failed")
if failed > 0:
    sys.exit(1)
