# Generated by generate_emit_runner.mjs. DO NOT EDIT.
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from generated import *
from specodec.msgpack_reader import MsgPackReader
from specodec.msgpack_writer import MsgPackWriter
from specodec.json_reader import JsonReader
from specodec.json_writer import JsonWriter
from specodec.gron_reader import GronReader
from specodec.gron_writer import GronWriter


def test_model_edge_empty(vec, out):
    passed = 0
    failed = 0
    codec = EdgeEmptyCodec
    try:
        b = open(os.path.join(vec, "EdgeEmpty.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeEmpty.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeEmpty mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeEmpty.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeEmpty.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeEmpty json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeEmpty.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeEmpty.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeEmpty unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeEmpty.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeEmpty.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeEmpty gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_edge_one_opt(vec, out):
    passed = 0
    failed = 0
    codec = EdgeOneOptCodec
    try:
        b = open(os.path.join(vec, "EdgeOneOpt.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeOneOpt.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeOneOpt mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeOneOpt.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeOneOpt.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeOneOpt json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeOneOpt.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeOneOpt.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeOneOpt unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeOneOpt.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeOneOpt.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeOneOpt gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_edge_big_nums(vec, out):
    passed = 0
    failed = 0
    codec = EdgeBigNumsCodec
    try:
        b = open(os.path.join(vec, "EdgeBigNums.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeBigNums.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeBigNums mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeBigNums.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeBigNums.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeBigNums json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeBigNums.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeBigNums.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeBigNums unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeBigNums.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeBigNums.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeBigNums gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_edge_zero_vals(vec, out):
    passed = 0
    failed = 0
    codec = EdgeZeroValsCodec
    try:
        b = open(os.path.join(vec, "EdgeZeroVals.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeZeroVals.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeZeroVals mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeZeroVals.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeZeroVals.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeZeroVals json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeZeroVals.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeZeroVals.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeZeroVals unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeZeroVals.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeZeroVals.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeZeroVals gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_edge_nullable(vec, out):
    passed = 0
    failed = 0
    codec = EdgeNullableCodec
    try:
        b = open(os.path.join(vec, "EdgeNullable.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeNullable.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeNullable mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeNullable.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeNullable.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeNullable json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeNullable.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeNullable.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeNullable unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeNullable.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeNullable.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeNullable gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_edge_neg_zero(vec, out):
    passed = 0
    failed = 0
    codec = EdgeNegZeroCodec
    try:
        b = open(os.path.join(vec, "EdgeNegZero.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeNegZero.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeNegZero mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeNegZero.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeNegZero.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeNegZero json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeNegZero.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeNegZero.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeNegZero unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeNegZero.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeNegZero.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeNegZero gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_edge_null_byte(vec, out):
    passed = 0
    failed = 0
    codec = EdgeNullByteCodec
    try:
        b = open(os.path.join(vec, "EdgeNullByte.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeNullByte.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeNullByte mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeNullByte.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeNullByte.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeNullByte json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeNullByte.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeNullByte.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeNullByte unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeNullByte.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeNullByte.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeNullByte gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_edge_boundary(vec, out):
    passed = 0
    failed = 0
    codec = EdgeBoundaryCodec
    try:
        b = open(os.path.join(vec, "EdgeBoundary.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeBoundary.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeBoundary mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeBoundary.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeBoundary.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeBoundary json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeBoundary.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeBoundary.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeBoundary unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeBoundary.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeBoundary.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeBoundary gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_edge_str_len(vec, out):
    passed = 0
    failed = 0
    codec = EdgeStrLenCodec
    try:
        b = open(os.path.join(vec, "EdgeStrLen.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeStrLen.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeStrLen mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeStrLen.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeStrLen.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeStrLen json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeStrLen.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeStrLen.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeStrLen unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeStrLen.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeStrLen.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeStrLen gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_edge_bytes_len(vec, out):
    passed = 0
    failed = 0
    codec = EdgeBytesLenCodec
    try:
        b = open(os.path.join(vec, "EdgeBytesLen.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeBytesLen.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeBytesLen mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeBytesLen.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeBytesLen.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeBytesLen json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeBytesLen.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeBytesLen.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeBytesLen unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeBytesLen.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeBytesLen.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeBytesLen gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_edge_arr_empty(vec, out):
    passed = 0
    failed = 0
    codec = EdgeArrEmptyCodec
    try:
        b = open(os.path.join(vec, "EdgeArrEmpty.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeArrEmpty.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeArrEmpty mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeArrEmpty.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeArrEmpty.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeArrEmpty json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeArrEmpty.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeArrEmpty.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeArrEmpty unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeArrEmpty.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeArrEmpty.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeArrEmpty gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_edge_arr_boundary(vec, out):
    passed = 0
    failed = 0
    codec = EdgeArrBoundaryCodec
    try:
        b = open(os.path.join(vec, "EdgeArrBoundary.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeArrBoundary.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeArrBoundary mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeArrBoundary.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeArrBoundary.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeArrBoundary json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeArrBoundary.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeArrBoundary.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeArrBoundary unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EdgeArrBoundary.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EdgeArrBoundary.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EdgeArrBoundary gron: " + str(e))
        failed += 1
    return passed, failed
def run_AllTypes_Edge():
    passed = 0
    failed = 0
    vec = os.environ["VEC_DIR"]
    out = os.environ["OUT_DIR"]
    os.makedirs(out, exist_ok=True)

    # Object tests
    p, f = test_model_edge_empty(vec, out); passed += p; failed += f
    p, f = test_model_edge_one_opt(vec, out); passed += p; failed += f
    p, f = test_model_edge_big_nums(vec, out); passed += p; failed += f
    p, f = test_model_edge_zero_vals(vec, out); passed += p; failed += f
    p, f = test_model_edge_nullable(vec, out); passed += p; failed += f
    p, f = test_model_edge_neg_zero(vec, out); passed += p; failed += f
    p, f = test_model_edge_null_byte(vec, out); passed += p; failed += f
    p, f = test_model_edge_boundary(vec, out); passed += p; failed += f
    p, f = test_model_edge_str_len(vec, out); passed += p; failed += f
    p, f = test_model_edge_bytes_len(vec, out); passed += p; failed += f
    p, f = test_model_edge_arr_empty(vec, out); passed += p; failed += f
    p, f = test_model_edge_arr_boundary(vec, out); passed += p; failed += f
    return passed, failed
