# Generated by generate_emit_runner.mjs. DO NOT EDIT.
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from generated import *
from specodec.msgpack_reader import MsgPackReader
from specodec.msgpack_writer import MsgPackWriter
from specodec.json_reader import JsonReader
from specodec.json_writer import JsonWriter
from specodec.gron_reader import GronReader
from specodec.gron_writer import GronWriter


def test_scalar_int8_min(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/int8_min.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_int32()
        w = MsgPackWriter()
        w.write_int32(val)
        open(os.path.join(out, "scalars/int8_min.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL int8_min mp: " + str(e))
        return 0, 1

def test_scalar_int8_max(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/int8_max.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_int32()
        w = MsgPackWriter()
        w.write_int32(val)
        open(os.path.join(out, "scalars/int8_max.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL int8_max mp: " + str(e))
        return 0, 1

def test_scalar_int16_min(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/int16_min.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_int32()
        w = MsgPackWriter()
        w.write_int32(val)
        open(os.path.join(out, "scalars/int16_min.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL int16_min mp: " + str(e))
        return 0, 1

def test_scalar_int16_max(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/int16_max.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_int32()
        w = MsgPackWriter()
        w.write_int32(val)
        open(os.path.join(out, "scalars/int16_max.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL int16_max mp: " + str(e))
        return 0, 1

def test_scalar_int32_min(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/int32_min.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_int32()
        w = MsgPackWriter()
        w.write_int32(val)
        open(os.path.join(out, "scalars/int32_min.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL int32_min mp: " + str(e))
        return 0, 1

def test_scalar_int32_max(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/int32_max.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_int32()
        w = MsgPackWriter()
        w.write_int32(val)
        open(os.path.join(out, "scalars/int32_max.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL int32_max mp: " + str(e))
        return 0, 1

def test_scalar_int64_min(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/int64_min.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_int64()
        w = MsgPackWriter()
        w.write_int64(val)
        open(os.path.join(out, "scalars/int64_min.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL int64_min mp: " + str(e))
        return 0, 1

def test_scalar_int64_max(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/int64_max.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_int64()
        w = MsgPackWriter()
        w.write_int64(val)
        open(os.path.join(out, "scalars/int64_max.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL int64_max mp: " + str(e))
        return 0, 1

def test_scalar_uint8_max(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/uint8_max.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_uint32()
        w = MsgPackWriter()
        w.write_uint32(val)
        open(os.path.join(out, "scalars/uint8_max.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL uint8_max mp: " + str(e))
        return 0, 1

def test_scalar_uint16_max(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/uint16_max.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_uint32()
        w = MsgPackWriter()
        w.write_uint32(val)
        open(os.path.join(out, "scalars/uint16_max.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL uint16_max mp: " + str(e))
        return 0, 1

def test_scalar_uint32_max(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/uint32_max.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_uint32()
        w = MsgPackWriter()
        w.write_uint32(val)
        open(os.path.join(out, "scalars/uint32_max.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL uint32_max mp: " + str(e))
        return 0, 1

def test_scalar_uint64_max(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/uint64_max.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_uint64()
        w = MsgPackWriter()
        w.write_uint64(val)
        open(os.path.join(out, "scalars/uint64_max.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL uint64_max mp: " + str(e))
        return 0, 1

def test_scalar_float32_1_5(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/float32_1.5.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_float32()
        w = MsgPackWriter()
        w.write_float32(val)
        open(os.path.join(out, "scalars/float32_1.5.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL float32_1.5 mp: " + str(e))
        return 0, 1

def test_scalar_float32_neg_zero(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/float32_neg_zero.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_float32()
        w = MsgPackWriter()
        w.write_float32(val)
        open(os.path.join(out, "scalars/float32_neg_zero.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL float32_neg_zero mp: " + str(e))
        return 0, 1

def test_scalar_float32_inf(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/float32_inf.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_float32()
        w = MsgPackWriter()
        w.write_float32(val)
        open(os.path.join(out, "scalars/float32_inf.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL float32_inf mp: " + str(e))
        return 0, 1

def test_scalar_float32_neg_inf(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/float32_neg_inf.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_float32()
        w = MsgPackWriter()
        w.write_float32(val)
        open(os.path.join(out, "scalars/float32_neg_inf.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL float32_neg_inf mp: " + str(e))
        return 0, 1

def test_scalar_float32_nan(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/float32_nan.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_float32()
        w = MsgPackWriter()
        w.write_float32(val)
        open(os.path.join(out, "scalars/float32_nan.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL float32_nan mp: " + str(e))
        return 0, 1

def test_scalar_float64_pi(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/float64_pi.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_float64()
        w = MsgPackWriter()
        w.write_float64(val)
        open(os.path.join(out, "scalars/float64_pi.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL float64_pi mp: " + str(e))
        return 0, 1

def test_scalar_float64_neg_zero(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/float64_neg_zero.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_float64()
        w = MsgPackWriter()
        w.write_float64(val)
        open(os.path.join(out, "scalars/float64_neg_zero.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL float64_neg_zero mp: " + str(e))
        return 0, 1

def test_scalar_float64_inf(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/float64_inf.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_float64()
        w = MsgPackWriter()
        w.write_float64(val)
        open(os.path.join(out, "scalars/float64_inf.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL float64_inf mp: " + str(e))
        return 0, 1

def test_scalar_float64_neg_inf(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/float64_neg_inf.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_float64()
        w = MsgPackWriter()
        w.write_float64(val)
        open(os.path.join(out, "scalars/float64_neg_inf.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL float64_neg_inf mp: " + str(e))
        return 0, 1

def test_scalar_float64_nan(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/float64_nan.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_float64()
        w = MsgPackWriter()
        w.write_float64(val)
        open(os.path.join(out, "scalars/float64_nan.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL float64_nan mp: " + str(e))
        return 0, 1

def test_scalar_str_empty(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/str_empty.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_string()
        w = MsgPackWriter()
        w.write_string(val)
        open(os.path.join(out, "scalars/str_empty.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL str_empty mp: " + str(e))
        return 0, 1

def test_scalar_str_ascii(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/str_ascii.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_string()
        w = MsgPackWriter()
        w.write_string(val)
        open(os.path.join(out, "scalars/str_ascii.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL str_ascii mp: " + str(e))
        return 0, 1

def test_scalar_str_null_byte(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/str_null_byte.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_string()
        w = MsgPackWriter()
        w.write_string(val)
        open(os.path.join(out, "scalars/str_null_byte.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL str_null_byte mp: " + str(e))
        return 0, 1

def test_scalar_str_escape(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/str_escape.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_string()
        w = MsgPackWriter()
        w.write_string(val)
        open(os.path.join(out, "scalars/str_escape.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL str_escape mp: " + str(e))
        return 0, 1

def test_scalar_str_unicode(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/str_unicode.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_string()
        w = MsgPackWriter()
        w.write_string(val)
        open(os.path.join(out, "scalars/str_unicode.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL str_unicode mp: " + str(e))
        return 0, 1

def test_scalar_str_31(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/str_31.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_string()
        w = MsgPackWriter()
        w.write_string(val)
        open(os.path.join(out, "scalars/str_31.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL str_31 mp: " + str(e))
        return 0, 1

def test_scalar_str_32(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/str_32.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_string()
        w = MsgPackWriter()
        w.write_string(val)
        open(os.path.join(out, "scalars/str_32.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL str_32 mp: " + str(e))
        return 0, 1

def test_scalar_str_255(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/str_255.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_string()
        w = MsgPackWriter()
        w.write_string(val)
        open(os.path.join(out, "scalars/str_255.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL str_255 mp: " + str(e))
        return 0, 1

def test_scalar_str_256(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/str_256.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_string()
        w = MsgPackWriter()
        w.write_string(val)
        open(os.path.join(out, "scalars/str_256.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL str_256 mp: " + str(e))
        return 0, 1

def test_scalar_bytes_empty(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/bytes_empty.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_bytes()
        w = MsgPackWriter()
        w.write_bytes(val)
        open(os.path.join(out, "scalars/bytes_empty.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL bytes_empty mp: " + str(e))
        return 0, 1

def test_scalar_bytes_small(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/bytes_small.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_bytes()
        w = MsgPackWriter()
        w.write_bytes(val)
        open(os.path.join(out, "scalars/bytes_small.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL bytes_small mp: " + str(e))
        return 0, 1

def test_scalar_bytes_31(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/bytes_31.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_bytes()
        w = MsgPackWriter()
        w.write_bytes(val)
        open(os.path.join(out, "scalars/bytes_31.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL bytes_31 mp: " + str(e))
        return 0, 1

def test_scalar_bytes_32(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/bytes_32.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_bytes()
        w = MsgPackWriter()
        w.write_bytes(val)
        open(os.path.join(out, "scalars/bytes_32.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL bytes_32 mp: " + str(e))
        return 0, 1

def test_scalar_bytes_255(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/bytes_255.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_bytes()
        w = MsgPackWriter()
        w.write_bytes(val)
        open(os.path.join(out, "scalars/bytes_255.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL bytes_255 mp: " + str(e))
        return 0, 1

def test_scalar_bytes_256(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/bytes_256.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_bytes()
        w = MsgPackWriter()
        w.write_bytes(val)
        open(os.path.join(out, "scalars/bytes_256.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL bytes_256 mp: " + str(e))
        return 0, 1

def test_scalar_bytes_zeros(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/bytes_zeros.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_bytes()
        w = MsgPackWriter()
        w.write_bytes(val)
        open(os.path.join(out, "scalars/bytes_zeros.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL bytes_zeros mp: " + str(e))
        return 0, 1

def test_scalar_bytes_ff(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/bytes_ff.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_bytes()
        w = MsgPackWriter()
        w.write_bytes(val)
        open(os.path.join(out, "scalars/bytes_ff.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL bytes_ff mp: " + str(e))
        return 0, 1

def test_scalar_bool_true(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/bool_true.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_bool()
        w = MsgPackWriter()
        w.write_bool(val)
        open(os.path.join(out, "scalars/bool_true.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL bool_true mp: " + str(e))
        return 0, 1

def test_scalar_bool_false(vec, out):
    try:
        b = open(os.path.join(vec, "scalars/bool_false.mp"), "rb").read()
        r = MsgPackReader(b)
        val = r.read_bool()
        w = MsgPackWriter()
        w.write_bool(val)
        open(os.path.join(out, "scalars/bool_false.mp"), "wb").write(w.to_bytes())
        return 1, 0
    except Exception as e:
        print("FAIL bool_false mp: " + str(e))
        return 0, 1
def run_scalars():
    passed = 0
    failed = 0
    vec = os.environ["VEC_DIR"]
    out = os.environ["OUT_DIR"]
    os.makedirs(out, exist_ok=True)
    os.makedirs(os.path.join(out, "scalars"), exist_ok=True)

    # Scalar tests
    p, f = test_scalar_int8_min(vec, out); passed += p; failed += f
    p, f = test_scalar_int8_max(vec, out); passed += p; failed += f
    p, f = test_scalar_int16_min(vec, out); passed += p; failed += f
    p, f = test_scalar_int16_max(vec, out); passed += p; failed += f
    p, f = test_scalar_int32_min(vec, out); passed += p; failed += f
    p, f = test_scalar_int32_max(vec, out); passed += p; failed += f
    p, f = test_scalar_int64_min(vec, out); passed += p; failed += f
    p, f = test_scalar_int64_max(vec, out); passed += p; failed += f
    p, f = test_scalar_uint8_max(vec, out); passed += p; failed += f
    p, f = test_scalar_uint16_max(vec, out); passed += p; failed += f
    p, f = test_scalar_uint32_max(vec, out); passed += p; failed += f
    p, f = test_scalar_uint64_max(vec, out); passed += p; failed += f
    p, f = test_scalar_float32_1_5(vec, out); passed += p; failed += f
    p, f = test_scalar_float32_neg_zero(vec, out); passed += p; failed += f
    p, f = test_scalar_float32_inf(vec, out); passed += p; failed += f
    p, f = test_scalar_float32_neg_inf(vec, out); passed += p; failed += f
    p, f = test_scalar_float32_nan(vec, out); passed += p; failed += f
    p, f = test_scalar_float64_pi(vec, out); passed += p; failed += f
    p, f = test_scalar_float64_neg_zero(vec, out); passed += p; failed += f
    p, f = test_scalar_float64_inf(vec, out); passed += p; failed += f
    p, f = test_scalar_float64_neg_inf(vec, out); passed += p; failed += f
    p, f = test_scalar_float64_nan(vec, out); passed += p; failed += f
    p, f = test_scalar_str_empty(vec, out); passed += p; failed += f
    p, f = test_scalar_str_ascii(vec, out); passed += p; failed += f
    p, f = test_scalar_str_null_byte(vec, out); passed += p; failed += f
    p, f = test_scalar_str_escape(vec, out); passed += p; failed += f
    p, f = test_scalar_str_unicode(vec, out); passed += p; failed += f
    p, f = test_scalar_str_31(vec, out); passed += p; failed += f
    p, f = test_scalar_str_32(vec, out); passed += p; failed += f
    p, f = test_scalar_str_255(vec, out); passed += p; failed += f
    p, f = test_scalar_str_256(vec, out); passed += p; failed += f
    p, f = test_scalar_bytes_empty(vec, out); passed += p; failed += f
    p, f = test_scalar_bytes_small(vec, out); passed += p; failed += f
    p, f = test_scalar_bytes_31(vec, out); passed += p; failed += f
    p, f = test_scalar_bytes_32(vec, out); passed += p; failed += f
    p, f = test_scalar_bytes_255(vec, out); passed += p; failed += f
    p, f = test_scalar_bytes_256(vec, out); passed += p; failed += f
    p, f = test_scalar_bytes_zeros(vec, out); passed += p; failed += f
    p, f = test_scalar_bytes_ff(vec, out); passed += p; failed += f
    p, f = test_scalar_bool_true(vec, out); passed += p; failed += f
    p, f = test_scalar_bool_false(vec, out); passed += p; failed += f
    return passed, failed
