# Generated by generate_emit_runner.mjs. DO NOT EDIT.
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from generated import *
from specodec.msgpack_reader import MsgPackReader
from specodec.msgpack_writer import MsgPackWriter
from specodec.json_reader import JsonReader
from specodec.json_writer import JsonWriter
from specodec.gron_reader import GronReader
from specodec.gron_writer import GronWriter


def test_model_arr_string(vec, out):
    passed = 0
    failed = 0
    codec = ArrStringCodec
    try:
        b = open(os.path.join(vec, "ArrString.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrString.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrString mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ArrString.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrString.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrString json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ArrString.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrString.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrString unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ArrString.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrString.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrString gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_arr_int32(vec, out):
    passed = 0
    failed = 0
    codec = ArrInt32Codec
    try:
        b = open(os.path.join(vec, "ArrInt32.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrInt32.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrInt32 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ArrInt32.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrInt32.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrInt32 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ArrInt32.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrInt32.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrInt32 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ArrInt32.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrInt32.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrInt32 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_arr_boolean(vec, out):
    passed = 0
    failed = 0
    codec = ArrBooleanCodec
    try:
        b = open(os.path.join(vec, "ArrBoolean.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrBoolean.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrBoolean mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ArrBoolean.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrBoolean.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrBoolean json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ArrBoolean.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrBoolean.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrBoolean unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ArrBoolean.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrBoolean.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrBoolean gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_arr_float64(vec, out):
    passed = 0
    failed = 0
    codec = ArrFloat64Codec
    try:
        b = open(os.path.join(vec, "ArrFloat64.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrFloat64.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrFloat64 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ArrFloat64.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrFloat64.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrFloat64 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ArrFloat64.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrFloat64.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrFloat64 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ArrFloat64.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrFloat64.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrFloat64 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_arr_bytes(vec, out):
    passed = 0
    failed = 0
    codec = ArrBytesCodec
    try:
        b = open(os.path.join(vec, "ArrBytes.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrBytes.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrBytes mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ArrBytes.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrBytes.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrBytes json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ArrBytes.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrBytes.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrBytes unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ArrBytes.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrBytes.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrBytes gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_arr_int64(vec, out):
    passed = 0
    failed = 0
    codec = ArrInt64Codec
    try:
        b = open(os.path.join(vec, "ArrInt64.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrInt64.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrInt64 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ArrInt64.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrInt64.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrInt64 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ArrInt64.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrInt64.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrInt64 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ArrInt64.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrInt64.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrInt64 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_arr_uint64(vec, out):
    passed = 0
    failed = 0
    codec = ArrUint64Codec
    try:
        b = open(os.path.join(vec, "ArrUint64.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrUint64.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrUint64 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ArrUint64.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrUint64.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrUint64 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ArrUint64.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrUint64.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrUint64 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ArrUint64.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ArrUint64.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ArrUint64 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_multi_arr1(vec, out):
    passed = 0
    failed = 0
    codec = MultiArr1Codec
    try:
        b = open(os.path.join(vec, "MultiArr1.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MultiArr1.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MultiArr1 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MultiArr1.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MultiArr1.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MultiArr1 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MultiArr1.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MultiArr1.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MultiArr1 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MultiArr1.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MultiArr1.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MultiArr1 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_multi_arr2(vec, out):
    passed = 0
    failed = 0
    codec = MultiArr2Codec
    try:
        b = open(os.path.join(vec, "MultiArr2.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MultiArr2.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MultiArr2 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MultiArr2.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MultiArr2.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MultiArr2 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MultiArr2.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MultiArr2.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MultiArr2 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MultiArr2.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MultiArr2.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MultiArr2 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_multi_arr3(vec, out):
    passed = 0
    failed = 0
    codec = MultiArr3Codec
    try:
        b = open(os.path.join(vec, "MultiArr3.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MultiArr3.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MultiArr3 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MultiArr3.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MultiArr3.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MultiArr3 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MultiArr3.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MultiArr3.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MultiArr3 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MultiArr3.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MultiArr3.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MultiArr3 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_multi_arr4(vec, out):
    passed = 0
    failed = 0
    codec = MultiArr4Codec
    try:
        b = open(os.path.join(vec, "MultiArr4.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MultiArr4.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MultiArr4 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MultiArr4.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MultiArr4.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MultiArr4 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MultiArr4.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MultiArr4.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MultiArr4 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MultiArr4.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MultiArr4.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MultiArr4 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_multi_arr5(vec, out):
    passed = 0
    failed = 0
    codec = MultiArr5Codec
    try:
        b = open(os.path.join(vec, "MultiArr5.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MultiArr5.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MultiArr5 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MultiArr5.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MultiArr5.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MultiArr5 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MultiArr5.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MultiArr5.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MultiArr5 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MultiArr5.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MultiArr5.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MultiArr5 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_combo1(vec, out):
    passed = 0
    failed = 0
    codec = OptCombo1Codec
    try:
        b = open(os.path.join(vec, "OptCombo1.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo1.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo1 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo1.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo1.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo1 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo1.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo1.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo1 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo1.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo1.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo1 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_combo2(vec, out):
    passed = 0
    failed = 0
    codec = OptCombo2Codec
    try:
        b = open(os.path.join(vec, "OptCombo2.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo2.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo2 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo2.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo2.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo2 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo2.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo2.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo2 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo2.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo2.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo2 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_combo3(vec, out):
    passed = 0
    failed = 0
    codec = OptCombo3Codec
    try:
        b = open(os.path.join(vec, "OptCombo3.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo3.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo3 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo3.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo3.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo3 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo3.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo3.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo3 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo3.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo3.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo3 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_combo4(vec, out):
    passed = 0
    failed = 0
    codec = OptCombo4Codec
    try:
        b = open(os.path.join(vec, "OptCombo4.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo4.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo4 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo4.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo4.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo4 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo4.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo4.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo4 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo4.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo4.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo4 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_combo5(vec, out):
    passed = 0
    failed = 0
    codec = OptCombo5Codec
    try:
        b = open(os.path.join(vec, "OptCombo5.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo5.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo5 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo5.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo5.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo5 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo5.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo5.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo5 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo5.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo5.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo5 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_combo6(vec, out):
    passed = 0
    failed = 0
    codec = OptCombo6Codec
    try:
        b = open(os.path.join(vec, "OptCombo6.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo6.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo6 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo6.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo6.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo6 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo6.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo6.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo6 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo6.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo6.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo6 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_combo7(vec, out):
    passed = 0
    failed = 0
    codec = OptCombo7Codec
    try:
        b = open(os.path.join(vec, "OptCombo7.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo7.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo7 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo7.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo7.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo7 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo7.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo7.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo7 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo7.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo7.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo7 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_combo8(vec, out):
    passed = 0
    failed = 0
    codec = OptCombo8Codec
    try:
        b = open(os.path.join(vec, "OptCombo8.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo8.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo8 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo8.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo8.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo8 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo8.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo8.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo8 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo8.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo8.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo8 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_combo9(vec, out):
    passed = 0
    failed = 0
    codec = OptCombo9Codec
    try:
        b = open(os.path.join(vec, "OptCombo9.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo9.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo9 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo9.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo9.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo9 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo9.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo9.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo9 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo9.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo9.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo9 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_combo10(vec, out):
    passed = 0
    failed = 0
    codec = OptCombo10Codec
    try:
        b = open(os.path.join(vec, "OptCombo10.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo10.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo10 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo10.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo10.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo10 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo10.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo10.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo10 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptCombo10.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptCombo10.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptCombo10 gron: " + str(e))
        failed += 1
    return passed, failed
def run_AllTypes_Arrays():
    passed = 0
    failed = 0
    vec = os.environ["VEC_DIR"]
    out = os.environ["OUT_DIR"]
    os.makedirs(out, exist_ok=True)

    # Object tests
    p, f = test_model_arr_string(vec, out); passed += p; failed += f
    p, f = test_model_arr_int32(vec, out); passed += p; failed += f
    p, f = test_model_arr_boolean(vec, out); passed += p; failed += f
    p, f = test_model_arr_float64(vec, out); passed += p; failed += f
    p, f = test_model_arr_bytes(vec, out); passed += p; failed += f
    p, f = test_model_arr_int64(vec, out); passed += p; failed += f
    p, f = test_model_arr_uint64(vec, out); passed += p; failed += f
    p, f = test_model_multi_arr1(vec, out); passed += p; failed += f
    p, f = test_model_multi_arr2(vec, out); passed += p; failed += f
    p, f = test_model_multi_arr3(vec, out); passed += p; failed += f
    p, f = test_model_multi_arr4(vec, out); passed += p; failed += f
    p, f = test_model_multi_arr5(vec, out); passed += p; failed += f
    p, f = test_model_opt_combo1(vec, out); passed += p; failed += f
    p, f = test_model_opt_combo2(vec, out); passed += p; failed += f
    p, f = test_model_opt_combo3(vec, out); passed += p; failed += f
    p, f = test_model_opt_combo4(vec, out); passed += p; failed += f
    p, f = test_model_opt_combo5(vec, out); passed += p; failed += f
    p, f = test_model_opt_combo6(vec, out); passed += p; failed += f
    p, f = test_model_opt_combo7(vec, out); passed += p; failed += f
    p, f = test_model_opt_combo8(vec, out); passed += p; failed += f
    p, f = test_model_opt_combo9(vec, out); passed += p; failed += f
    p, f = test_model_opt_combo10(vec, out); passed += p; failed += f
    return passed, failed
