# Generated by generate_emit_runner.mjs. DO NOT EDIT.
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from generated import *
from specodec.msgpack_reader import MsgPackReader
from specodec.msgpack_writer import MsgPackWriter
from specodec.json_reader import JsonReader
from specodec.json_writer import JsonWriter
from specodec.gron_reader import GronReader
from specodec.gron_writer import GronWriter


def test_model_enum_holder(vec, out):
    passed = 0
    failed = 0
    codec = EnumHolderCodec
    try:
        b = open(os.path.join(vec, "EnumHolder.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EnumHolder.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EnumHolder mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EnumHolder.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EnumHolder.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EnumHolder json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EnumHolder.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EnumHolder.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EnumHolder unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EnumHolder.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EnumHolder.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EnumHolder gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_enum_holder(vec, out):
    passed = 0
    failed = 0
    codec = OptEnumHolderCodec
    try:
        b = open(os.path.join(vec, "OptEnumHolder.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptEnumHolder.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptEnumHolder mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptEnumHolder.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptEnumHolder.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptEnumHolder json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptEnumHolder.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptEnumHolder.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptEnumHolder unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptEnumHolder.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptEnumHolder.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptEnumHolder gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_enum_array_holder(vec, out):
    passed = 0
    failed = 0
    codec = EnumArrayHolderCodec
    try:
        b = open(os.path.join(vec, "EnumArrayHolder.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EnumArrayHolder.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EnumArrayHolder mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EnumArrayHolder.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EnumArrayHolder.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EnumArrayHolder json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EnumArrayHolder.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EnumArrayHolder.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EnumArrayHolder unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EnumArrayHolder.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EnumArrayHolder.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EnumArrayHolder gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_enum_mixed_holder(vec, out):
    passed = 0
    failed = 0
    codec = EnumMixedHolderCodec
    try:
        b = open(os.path.join(vec, "EnumMixedHolder.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EnumMixedHolder.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EnumMixedHolder mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EnumMixedHolder.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EnumMixedHolder.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EnumMixedHolder json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EnumMixedHolder.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EnumMixedHolder.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EnumMixedHolder unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "EnumMixedHolder.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "EnumMixedHolder.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL EnumMixedHolder gron: " + str(e))
        failed += 1
    return passed, failed
def run_AllTypes_Enums():
    passed = 0
    failed = 0
    vec = os.environ["VEC_DIR"]
    out = os.environ["OUT_DIR"]
    os.makedirs(out, exist_ok=True)

    # Object tests
    p, f = test_model_enum_holder(vec, out); passed += p; failed += f
    p, f = test_model_opt_enum_holder(vec, out); passed += p; failed += f
    p, f = test_model_enum_array_holder(vec, out); passed += p; failed += f
    p, f = test_model_enum_mixed_holder(vec, out); passed += p; failed += f
    return passed, failed
