# Generated by generate_emit_runner.mjs. DO NOT EDIT.
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from generated import *
from specodec.msgpack_reader import MsgPackReader
from specodec.msgpack_writer import MsgPackWriter
from specodec.json_reader import JsonReader
from specodec.json_writer import JsonWriter
from specodec.gron_reader import GronReader
from specodec.gron_writer import GronWriter


def test_model_shape_circle(vec, out):
    passed = 0
    failed = 0
    codec = ShapeCodec
    try:
        b = open(os.path.join(vec, "Shape_circle.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Shape_circle.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Shape_circle mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Shape_circle.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Shape_circle.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Shape_circle json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Shape_circle.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Shape_circle.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Shape_circle unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Shape_circle.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Shape_circle.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Shape_circle gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_shape_rect(vec, out):
    passed = 0
    failed = 0
    codec = ShapeCodec
    try:
        b = open(os.path.join(vec, "Shape_rect.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Shape_rect.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Shape_rect mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Shape_rect.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Shape_rect.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Shape_rect json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Shape_rect.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Shape_rect.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Shape_rect unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Shape_rect.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Shape_rect.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Shape_rect gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_ident_name(vec, out):
    passed = 0
    failed = 0
    codec = IdentCodec
    try:
        b = open(os.path.join(vec, "Ident_name.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ident_name.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ident_name mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Ident_name.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ident_name.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ident_name json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Ident_name.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ident_name.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ident_name unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Ident_name.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ident_name.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ident_name gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_ident_number(vec, out):
    passed = 0
    failed = 0
    codec = IdentCodec
    try:
        b = open(os.path.join(vec, "Ident_number.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ident_number.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ident_number mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Ident_number.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ident_number.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ident_number json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Ident_number.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ident_number.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ident_number unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Ident_number.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ident_number.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ident_number gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_result_msg_ok(vec, out):
    passed = 0
    failed = 0
    codec = ResultMsgCodec
    try:
        b = open(os.path.join(vec, "ResultMsg_ok.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ResultMsg_ok.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ResultMsg_ok mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ResultMsg_ok.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ResultMsg_ok.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ResultMsg_ok json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ResultMsg_ok.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ResultMsg_ok.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ResultMsg_ok unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ResultMsg_ok.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ResultMsg_ok.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ResultMsg_ok gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_result_msg_err(vec, out):
    passed = 0
    failed = 0
    codec = ResultMsgCodec
    try:
        b = open(os.path.join(vec, "ResultMsg_err.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ResultMsg_err.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ResultMsg_err mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ResultMsg_err.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ResultMsg_err.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ResultMsg_err json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ResultMsg_err.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ResultMsg_err.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ResultMsg_err unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ResultMsg_err.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ResultMsg_err.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ResultMsg_err gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_tagged_tag(vec, out):
    passed = 0
    failed = 0
    codec = TaggedCodec
    try:
        b = open(os.path.join(vec, "Tagged_tag.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Tagged_tag.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Tagged_tag mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Tagged_tag.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Tagged_tag.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Tagged_tag json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Tagged_tag.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Tagged_tag.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Tagged_tag unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Tagged_tag.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Tagged_tag.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Tagged_tag gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_tagged_score(vec, out):
    passed = 0
    failed = 0
    codec = TaggedCodec
    try:
        b = open(os.path.join(vec, "Tagged_score.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Tagged_score.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Tagged_score mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Tagged_score.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Tagged_score.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Tagged_score json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Tagged_score.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Tagged_score.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Tagged_score unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Tagged_score.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Tagged_score.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Tagged_score gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_tagged_active(vec, out):
    passed = 0
    failed = 0
    codec = TaggedCodec
    try:
        b = open(os.path.join(vec, "Tagged_active.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Tagged_active.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Tagged_active mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Tagged_active.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Tagged_active.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Tagged_active json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Tagged_active.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Tagged_active.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Tagged_active unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Tagged_active.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Tagged_active.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Tagged_active gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_union_holder_shape(vec, out):
    passed = 0
    failed = 0
    codec = OptUnionHolderCodec
    try:
        b = open(os.path.join(vec, "OptUnionHolder_shape.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptUnionHolder_shape.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptUnionHolder_shape mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptUnionHolder_shape.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptUnionHolder_shape.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptUnionHolder_shape json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptUnionHolder_shape.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptUnionHolder_shape.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptUnionHolder_shape unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptUnionHolder_shape.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptUnionHolder_shape.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptUnionHolder_shape gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_union_holder_id(vec, out):
    passed = 0
    failed = 0
    codec = OptUnionHolderCodec
    try:
        b = open(os.path.join(vec, "OptUnionHolder_id.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptUnionHolder_id.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptUnionHolder_id mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptUnionHolder_id.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptUnionHolder_id.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptUnionHolder_id json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptUnionHolder_id.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptUnionHolder_id.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptUnionHolder_id unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptUnionHolder_id.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptUnionHolder_id.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptUnionHolder_id gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_mixed_union_point(vec, out):
    passed = 0
    failed = 0
    codec = MixedUnionCodec
    try:
        b = open(os.path.join(vec, "MixedUnion_point.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MixedUnion_point.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MixedUnion_point mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MixedUnion_point.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MixedUnion_point.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MixedUnion_point json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MixedUnion_point.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MixedUnion_point.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MixedUnion_point unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MixedUnion_point.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MixedUnion_point.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MixedUnion_point gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_mixed_union_label(vec, out):
    passed = 0
    failed = 0
    codec = MixedUnionCodec
    try:
        b = open(os.path.join(vec, "MixedUnion_label.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MixedUnion_label.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MixedUnion_label mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MixedUnion_label.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MixedUnion_label.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MixedUnion_label json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MixedUnion_label.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MixedUnion_label.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MixedUnion_label unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MixedUnion_label.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MixedUnion_label.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MixedUnion_label gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_mixed_union_count(vec, out):
    passed = 0
    failed = 0
    codec = MixedUnionCodec
    try:
        b = open(os.path.join(vec, "MixedUnion_count.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MixedUnion_count.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MixedUnion_count mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MixedUnion_count.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MixedUnion_count.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MixedUnion_count json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MixedUnion_count.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MixedUnion_count.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MixedUnion_count unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "MixedUnion_count.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "MixedUnion_count.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL MixedUnion_count gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_nested_union_result(vec, out):
    passed = 0
    failed = 0
    codec = NestedUnionCodec
    try:
        b = open(os.path.join(vec, "NestedUnion_result.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestedUnion_result.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestedUnion_result mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestedUnion_result.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestedUnion_result.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestedUnion_result json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestedUnion_result.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestedUnion_result.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestedUnion_result unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestedUnion_result.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestedUnion_result.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestedUnion_result gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_nested_union_shape(vec, out):
    passed = 0
    failed = 0
    codec = NestedUnionCodec
    try:
        b = open(os.path.join(vec, "NestedUnion_shape.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestedUnion_shape.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestedUnion_shape mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestedUnion_shape.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestedUnion_shape.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestedUnion_shape json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestedUnion_shape.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestedUnion_shape.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestedUnion_shape unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestedUnion_shape.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestedUnion_shape.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestedUnion_shape gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_scalar_union_s(vec, out):
    passed = 0
    failed = 0
    codec = ScalarUnionCodec
    try:
        b = open(os.path.join(vec, "ScalarUnion_s.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ScalarUnion_s.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ScalarUnion_s mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ScalarUnion_s.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ScalarUnion_s.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ScalarUnion_s json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ScalarUnion_s.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ScalarUnion_s.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ScalarUnion_s unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ScalarUnion_s.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ScalarUnion_s.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ScalarUnion_s gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_scalar_union_i(vec, out):
    passed = 0
    failed = 0
    codec = ScalarUnionCodec
    try:
        b = open(os.path.join(vec, "ScalarUnion_i.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ScalarUnion_i.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ScalarUnion_i mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ScalarUnion_i.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ScalarUnion_i.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ScalarUnion_i json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ScalarUnion_i.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ScalarUnion_i.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ScalarUnion_i unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ScalarUnion_i.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ScalarUnion_i.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ScalarUnion_i gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_scalar_union_f(vec, out):
    passed = 0
    failed = 0
    codec = ScalarUnionCodec
    try:
        b = open(os.path.join(vec, "ScalarUnion_f.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ScalarUnion_f.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ScalarUnion_f mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ScalarUnion_f.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ScalarUnion_f.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ScalarUnion_f json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ScalarUnion_f.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ScalarUnion_f.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ScalarUnion_f unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ScalarUnion_f.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ScalarUnion_f.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ScalarUnion_f gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_scalar_union_b(vec, out):
    passed = 0
    failed = 0
    codec = ScalarUnionCodec
    try:
        b = open(os.path.join(vec, "ScalarUnion_b.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ScalarUnion_b.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ScalarUnion_b mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ScalarUnion_b.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ScalarUnion_b.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ScalarUnion_b json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ScalarUnion_b.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ScalarUnion_b.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ScalarUnion_b unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ScalarUnion_b.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ScalarUnion_b.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ScalarUnion_b gron: " + str(e))
        failed += 1
    return passed, failed
def run_models():
    passed = 0
    failed = 0
    vec = os.environ["VEC_DIR"]
    out = os.environ["OUT_DIR"]
    os.makedirs(out, exist_ok=True)

    # Object tests
    p, f = test_model_shape_circle(vec, out); passed += p; failed += f
    p, f = test_model_shape_rect(vec, out); passed += p; failed += f
    p, f = test_model_ident_name(vec, out); passed += p; failed += f
    p, f = test_model_ident_number(vec, out); passed += p; failed += f
    p, f = test_model_result_msg_ok(vec, out); passed += p; failed += f
    p, f = test_model_result_msg_err(vec, out); passed += p; failed += f
    p, f = test_model_tagged_tag(vec, out); passed += p; failed += f
    p, f = test_model_tagged_score(vec, out); passed += p; failed += f
    p, f = test_model_tagged_active(vec, out); passed += p; failed += f
    p, f = test_model_opt_union_holder_shape(vec, out); passed += p; failed += f
    p, f = test_model_opt_union_holder_id(vec, out); passed += p; failed += f
    p, f = test_model_mixed_union_point(vec, out); passed += p; failed += f
    p, f = test_model_mixed_union_label(vec, out); passed += p; failed += f
    p, f = test_model_mixed_union_count(vec, out); passed += p; failed += f
    p, f = test_model_nested_union_result(vec, out); passed += p; failed += f
    p, f = test_model_nested_union_shape(vec, out); passed += p; failed += f
    p, f = test_model_scalar_union_s(vec, out); passed += p; failed += f
    p, f = test_model_scalar_union_i(vec, out); passed += p; failed += f
    p, f = test_model_scalar_union_f(vec, out); passed += p; failed += f
    p, f = test_model_scalar_union_b(vec, out); passed += p; failed += f
    return passed, failed
