# Generated by generate_emit_runner.mjs. DO NOT EDIT.
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from generated import *
from specodec.msgpack_reader import MsgPackReader
from specodec.msgpack_writer import MsgPackWriter
from specodec.json_reader import JsonReader
from specodec.json_writer import JsonWriter
from specodec.gron_reader import GronReader
from specodec.gron_writer import GronWriter


def test_model_opt_single_string(vec, out):
    passed = 0
    failed = 0
    codec = OptSingleStringCodec
    try:
        b = open(os.path.join(vec, "OptSingleString.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleString.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleString mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleString.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleString.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleString json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleString.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleString.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleString unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleString.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleString.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleString gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_single_boolean(vec, out):
    passed = 0
    failed = 0
    codec = OptSingleBooleanCodec
    try:
        b = open(os.path.join(vec, "OptSingleBoolean.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleBoolean.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleBoolean mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleBoolean.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleBoolean.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleBoolean json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleBoolean.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleBoolean.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleBoolean unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleBoolean.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleBoolean.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleBoolean gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_single_int8(vec, out):
    passed = 0
    failed = 0
    codec = OptSingleInt8Codec
    try:
        b = open(os.path.join(vec, "OptSingleInt8.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleInt8.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleInt8 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleInt8.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleInt8.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleInt8 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleInt8.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleInt8.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleInt8 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleInt8.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleInt8.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleInt8 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_single_int16(vec, out):
    passed = 0
    failed = 0
    codec = OptSingleInt16Codec
    try:
        b = open(os.path.join(vec, "OptSingleInt16.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleInt16.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleInt16 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleInt16.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleInt16.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleInt16 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleInt16.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleInt16.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleInt16 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleInt16.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleInt16.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleInt16 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_single_int32(vec, out):
    passed = 0
    failed = 0
    codec = OptSingleInt32Codec
    try:
        b = open(os.path.join(vec, "OptSingleInt32.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleInt32.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleInt32 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleInt32.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleInt32.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleInt32 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleInt32.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleInt32.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleInt32 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleInt32.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleInt32.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleInt32 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_single_int64(vec, out):
    passed = 0
    failed = 0
    codec = OptSingleInt64Codec
    try:
        b = open(os.path.join(vec, "OptSingleInt64.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleInt64.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleInt64 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleInt64.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleInt64.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleInt64 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleInt64.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleInt64.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleInt64 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleInt64.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleInt64.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleInt64 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_single_uint8(vec, out):
    passed = 0
    failed = 0
    codec = OptSingleUint8Codec
    try:
        b = open(os.path.join(vec, "OptSingleUint8.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleUint8.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleUint8 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleUint8.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleUint8.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleUint8 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleUint8.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleUint8.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleUint8 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleUint8.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleUint8.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleUint8 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_single_uint16(vec, out):
    passed = 0
    failed = 0
    codec = OptSingleUint16Codec
    try:
        b = open(os.path.join(vec, "OptSingleUint16.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleUint16.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleUint16 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleUint16.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleUint16.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleUint16 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleUint16.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleUint16.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleUint16 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleUint16.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleUint16.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleUint16 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_single_uint32(vec, out):
    passed = 0
    failed = 0
    codec = OptSingleUint32Codec
    try:
        b = open(os.path.join(vec, "OptSingleUint32.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleUint32.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleUint32 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleUint32.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleUint32.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleUint32 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleUint32.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleUint32.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleUint32 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleUint32.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleUint32.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleUint32 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_single_uint64(vec, out):
    passed = 0
    failed = 0
    codec = OptSingleUint64Codec
    try:
        b = open(os.path.join(vec, "OptSingleUint64.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleUint64.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleUint64 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleUint64.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleUint64.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleUint64 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleUint64.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleUint64.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleUint64 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleUint64.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleUint64.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleUint64 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_single_float32(vec, out):
    passed = 0
    failed = 0
    codec = OptSingleFloat32Codec
    try:
        b = open(os.path.join(vec, "OptSingleFloat32.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleFloat32.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleFloat32 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleFloat32.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleFloat32.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleFloat32 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleFloat32.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleFloat32.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleFloat32 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleFloat32.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleFloat32.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleFloat32 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_single_float64(vec, out):
    passed = 0
    failed = 0
    codec = OptSingleFloat64Codec
    try:
        b = open(os.path.join(vec, "OptSingleFloat64.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleFloat64.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleFloat64 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleFloat64.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleFloat64.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleFloat64 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleFloat64.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleFloat64.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleFloat64 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleFloat64.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleFloat64.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleFloat64 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_single_bytes(vec, out):
    passed = 0
    failed = 0
    codec = OptSingleBytesCodec
    try:
        b = open(os.path.join(vec, "OptSingleBytes.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleBytes.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleBytes mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleBytes.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleBytes.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleBytes json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleBytes.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleBytes.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleBytes unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptSingleBytes.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptSingleBytes.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptSingleBytes gron: " + str(e))
        failed += 1
    return passed, failed
def run_AllTypes_Opt():
    passed = 0
    failed = 0
    vec = os.environ["VEC_DIR"]
    out = os.environ["OUT_DIR"]
    os.makedirs(out, exist_ok=True)

    # Object tests
    p, f = test_model_opt_single_string(vec, out); passed += p; failed += f
    p, f = test_model_opt_single_boolean(vec, out); passed += p; failed += f
    p, f = test_model_opt_single_int8(vec, out); passed += p; failed += f
    p, f = test_model_opt_single_int16(vec, out); passed += p; failed += f
    p, f = test_model_opt_single_int32(vec, out); passed += p; failed += f
    p, f = test_model_opt_single_int64(vec, out); passed += p; failed += f
    p, f = test_model_opt_single_uint8(vec, out); passed += p; failed += f
    p, f = test_model_opt_single_uint16(vec, out); passed += p; failed += f
    p, f = test_model_opt_single_uint32(vec, out); passed += p; failed += f
    p, f = test_model_opt_single_uint64(vec, out); passed += p; failed += f
    p, f = test_model_opt_single_float32(vec, out); passed += p; failed += f
    p, f = test_model_opt_single_float64(vec, out); passed += p; failed += f
    p, f = test_model_opt_single_bytes(vec, out); passed += p; failed += f
    return passed, failed
