# Generated by generate_emit_runner.mjs. DO NOT EDIT.
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from generated import *
from specodec.msgpack_reader import MsgPackReader
from specodec.msgpack_writer import MsgPackWriter
from specodec.json_reader import JsonReader
from specodec.json_writer import JsonWriter
from specodec.gron_reader import GronReader
from specodec.gron_writer import GronWriter


def test_model_rec_list(vec, out):
    passed = 0
    failed = 0
    codec = RecListCodec
    try:
        b = open(os.path.join(vec, "RecList.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "RecList.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL RecList mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "RecList.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "RecList.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL RecList json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "RecList.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "RecList.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL RecList unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "RecList.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "RecList.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL RecList gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_rec_tree(vec, out):
    passed = 0
    failed = 0
    codec = RecTreeCodec
    try:
        b = open(os.path.join(vec, "RecTree.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "RecTree.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL RecTree mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "RecTree.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "RecTree.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL RecTree json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "RecTree.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "RecTree.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL RecTree unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "RecTree.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "RecTree.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL RecTree gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_rec_chain(vec, out):
    passed = 0
    failed = 0
    codec = RecChainCodec
    try:
        b = open(os.path.join(vec, "RecChain.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "RecChain.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL RecChain mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "RecChain.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "RecChain.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL RecChain json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "RecChain.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "RecChain.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL RecChain unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "RecChain.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "RecChain.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL RecChain gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_rec_wrap(vec, out):
    passed = 0
    failed = 0
    codec = RecWrapCodec
    try:
        b = open(os.path.join(vec, "RecWrap.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "RecWrap.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL RecWrap mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "RecWrap.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "RecWrap.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL RecWrap json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "RecWrap.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "RecWrap.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL RecWrap unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "RecWrap.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "RecWrap.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL RecWrap gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_rec_wide(vec, out):
    passed = 0
    failed = 0
    codec = RecWideCodec
    try:
        b = open(os.path.join(vec, "RecWide.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "RecWide.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL RecWide mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "RecWide.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "RecWide.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL RecWide json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "RecWide.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "RecWide.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL RecWide unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "RecWide.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "RecWide.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL RecWide gron: " + str(e))
        failed += 1
    return passed, failed
def run_AllTypes_Recursive():
    passed = 0
    failed = 0
    vec = os.environ["VEC_DIR"]
    out = os.environ["OUT_DIR"]
    os.makedirs(out, exist_ok=True)

    # Object tests
    p, f = test_model_rec_list(vec, out); passed += p; failed += f
    p, f = test_model_rec_tree(vec, out); passed += p; failed += f
    p, f = test_model_rec_chain(vec, out); passed += p; failed += f
    p, f = test_model_rec_wrap(vec, out); passed += p; failed += f
    p, f = test_model_rec_wide(vec, out); passed += p; failed += f
    return passed, failed
