# Generated by generate_emit_runner.mjs. DO NOT EDIT.
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from generated import *
from specodec.msgpack_reader import MsgPackReader
from specodec.msgpack_writer import MsgPackWriter
from specodec.json_reader import JsonReader
from specodec.json_writer import JsonWriter
from specodec.gron_reader import GronReader
from specodec.gron_writer import GronWriter


def test_model_single_string(vec, out):
    passed = 0
    failed = 0
    codec = SingleStringCodec
    try:
        b = open(os.path.join(vec, "SingleString.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleString.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleString mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleString.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleString.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleString json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleString.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleString.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleString unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleString.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleString.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleString gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_single_boolean(vec, out):
    passed = 0
    failed = 0
    codec = SingleBooleanCodec
    try:
        b = open(os.path.join(vec, "SingleBoolean.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleBoolean.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleBoolean mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleBoolean.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleBoolean.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleBoolean json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleBoolean.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleBoolean.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleBoolean unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleBoolean.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleBoolean.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleBoolean gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_single_int8(vec, out):
    passed = 0
    failed = 0
    codec = SingleInt8Codec
    try:
        b = open(os.path.join(vec, "SingleInt8.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleInt8.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleInt8 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleInt8.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleInt8.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleInt8 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleInt8.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleInt8.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleInt8 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleInt8.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleInt8.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleInt8 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_single_int16(vec, out):
    passed = 0
    failed = 0
    codec = SingleInt16Codec
    try:
        b = open(os.path.join(vec, "SingleInt16.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleInt16.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleInt16 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleInt16.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleInt16.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleInt16 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleInt16.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleInt16.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleInt16 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleInt16.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleInt16.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleInt16 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_single_int32(vec, out):
    passed = 0
    failed = 0
    codec = SingleInt32Codec
    try:
        b = open(os.path.join(vec, "SingleInt32.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleInt32.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleInt32 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleInt32.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleInt32.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleInt32 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleInt32.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleInt32.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleInt32 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleInt32.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleInt32.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleInt32 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_single_int64(vec, out):
    passed = 0
    failed = 0
    codec = SingleInt64Codec
    try:
        b = open(os.path.join(vec, "SingleInt64.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleInt64.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleInt64 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleInt64.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleInt64.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleInt64 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleInt64.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleInt64.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleInt64 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleInt64.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleInt64.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleInt64 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_single_uint8(vec, out):
    passed = 0
    failed = 0
    codec = SingleUint8Codec
    try:
        b = open(os.path.join(vec, "SingleUint8.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleUint8.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleUint8 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleUint8.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleUint8.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleUint8 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleUint8.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleUint8.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleUint8 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleUint8.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleUint8.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleUint8 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_single_uint16(vec, out):
    passed = 0
    failed = 0
    codec = SingleUint16Codec
    try:
        b = open(os.path.join(vec, "SingleUint16.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleUint16.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleUint16 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleUint16.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleUint16.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleUint16 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleUint16.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleUint16.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleUint16 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleUint16.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleUint16.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleUint16 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_single_uint32(vec, out):
    passed = 0
    failed = 0
    codec = SingleUint32Codec
    try:
        b = open(os.path.join(vec, "SingleUint32.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleUint32.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleUint32 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleUint32.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleUint32.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleUint32 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleUint32.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleUint32.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleUint32 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleUint32.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleUint32.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleUint32 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_single_uint64(vec, out):
    passed = 0
    failed = 0
    codec = SingleUint64Codec
    try:
        b = open(os.path.join(vec, "SingleUint64.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleUint64.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleUint64 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleUint64.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleUint64.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleUint64 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleUint64.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleUint64.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleUint64 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleUint64.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleUint64.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleUint64 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_single_float32(vec, out):
    passed = 0
    failed = 0
    codec = SingleFloat32Codec
    try:
        b = open(os.path.join(vec, "SingleFloat32.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleFloat32.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleFloat32 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleFloat32.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleFloat32.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleFloat32 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleFloat32.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleFloat32.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleFloat32 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleFloat32.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleFloat32.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleFloat32 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_single_float64(vec, out):
    passed = 0
    failed = 0
    codec = SingleFloat64Codec
    try:
        b = open(os.path.join(vec, "SingleFloat64.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleFloat64.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleFloat64 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleFloat64.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleFloat64.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleFloat64 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleFloat64.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleFloat64.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleFloat64 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleFloat64.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleFloat64.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleFloat64 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_single_bytes(vec, out):
    passed = 0
    failed = 0
    codec = SingleBytesCodec
    try:
        b = open(os.path.join(vec, "SingleBytes.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleBytes.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleBytes mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleBytes.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleBytes.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleBytes json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleBytes.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleBytes.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleBytes unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "SingleBytes.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "SingleBytes.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL SingleBytes gron: " + str(e))
        failed += 1
    return passed, failed
def run_AllTypes_Scalars():
    passed = 0
    failed = 0
    vec = os.environ["VEC_DIR"]
    out = os.environ["OUT_DIR"]
    os.makedirs(out, exist_ok=True)

    # Object tests
    p, f = test_model_single_string(vec, out); passed += p; failed += f
    p, f = test_model_single_boolean(vec, out); passed += p; failed += f
    p, f = test_model_single_int8(vec, out); passed += p; failed += f
    p, f = test_model_single_int16(vec, out); passed += p; failed += f
    p, f = test_model_single_int32(vec, out); passed += p; failed += f
    p, f = test_model_single_int64(vec, out); passed += p; failed += f
    p, f = test_model_single_uint8(vec, out); passed += p; failed += f
    p, f = test_model_single_uint16(vec, out); passed += p; failed += f
    p, f = test_model_single_uint32(vec, out); passed += p; failed += f
    p, f = test_model_single_uint64(vec, out); passed += p; failed += f
    p, f = test_model_single_float32(vec, out); passed += p; failed += f
    p, f = test_model_single_float64(vec, out); passed += p; failed += f
    p, f = test_model_single_bytes(vec, out); passed += p; failed += f
    return passed, failed
