# Generated by generate_emit_runner.mjs. DO NOT EDIT.
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from generated import *
from specodec.msgpack_reader import MsgPackReader
from specodec.msgpack_writer import MsgPackWriter
from specodec.json_reader import JsonReader
from specodec.json_writer import JsonWriter
from specodec.gron_reader import GronReader
from specodec.gron_writer import GronWriter


def test_model_pair_string(vec, out):
    passed = 0
    failed = 0
    codec = PairStringCodec
    try:
        b = open(os.path.join(vec, "PairString.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairString.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairString mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairString.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairString.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairString json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairString.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairString.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairString unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairString.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairString.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairString gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_pair_boolean(vec, out):
    passed = 0
    failed = 0
    codec = PairBooleanCodec
    try:
        b = open(os.path.join(vec, "PairBoolean.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairBoolean.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairBoolean mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairBoolean.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairBoolean.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairBoolean json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairBoolean.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairBoolean.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairBoolean unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairBoolean.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairBoolean.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairBoolean gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_pair_int8(vec, out):
    passed = 0
    failed = 0
    codec = PairInt8Codec
    try:
        b = open(os.path.join(vec, "PairInt8.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairInt8.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairInt8 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairInt8.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairInt8.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairInt8 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairInt8.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairInt8.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairInt8 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairInt8.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairInt8.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairInt8 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_pair_int16(vec, out):
    passed = 0
    failed = 0
    codec = PairInt16Codec
    try:
        b = open(os.path.join(vec, "PairInt16.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairInt16.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairInt16 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairInt16.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairInt16.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairInt16 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairInt16.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairInt16.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairInt16 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairInt16.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairInt16.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairInt16 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_pair_int32(vec, out):
    passed = 0
    failed = 0
    codec = PairInt32Codec
    try:
        b = open(os.path.join(vec, "PairInt32.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairInt32.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairInt32 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairInt32.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairInt32.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairInt32 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairInt32.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairInt32.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairInt32 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairInt32.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairInt32.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairInt32 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_pair_int64(vec, out):
    passed = 0
    failed = 0
    codec = PairInt64Codec
    try:
        b = open(os.path.join(vec, "PairInt64.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairInt64.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairInt64 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairInt64.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairInt64.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairInt64 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairInt64.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairInt64.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairInt64 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairInt64.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairInt64.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairInt64 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_pair_uint8(vec, out):
    passed = 0
    failed = 0
    codec = PairUint8Codec
    try:
        b = open(os.path.join(vec, "PairUint8.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairUint8.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairUint8 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairUint8.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairUint8.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairUint8 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairUint8.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairUint8.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairUint8 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairUint8.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairUint8.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairUint8 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_pair_uint16(vec, out):
    passed = 0
    failed = 0
    codec = PairUint16Codec
    try:
        b = open(os.path.join(vec, "PairUint16.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairUint16.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairUint16 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairUint16.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairUint16.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairUint16 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairUint16.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairUint16.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairUint16 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairUint16.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairUint16.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairUint16 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_pair_uint32(vec, out):
    passed = 0
    failed = 0
    codec = PairUint32Codec
    try:
        b = open(os.path.join(vec, "PairUint32.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairUint32.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairUint32 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairUint32.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairUint32.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairUint32 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairUint32.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairUint32.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairUint32 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairUint32.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairUint32.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairUint32 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_pair_uint64(vec, out):
    passed = 0
    failed = 0
    codec = PairUint64Codec
    try:
        b = open(os.path.join(vec, "PairUint64.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairUint64.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairUint64 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairUint64.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairUint64.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairUint64 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairUint64.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairUint64.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairUint64 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairUint64.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairUint64.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairUint64 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_pair_float32(vec, out):
    passed = 0
    failed = 0
    codec = PairFloat32Codec
    try:
        b = open(os.path.join(vec, "PairFloat32.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairFloat32.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairFloat32 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairFloat32.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairFloat32.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairFloat32 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairFloat32.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairFloat32.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairFloat32 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairFloat32.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairFloat32.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairFloat32 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_pair_float64(vec, out):
    passed = 0
    failed = 0
    codec = PairFloat64Codec
    try:
        b = open(os.path.join(vec, "PairFloat64.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairFloat64.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairFloat64 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairFloat64.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairFloat64.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairFloat64 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairFloat64.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairFloat64.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairFloat64 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairFloat64.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairFloat64.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairFloat64 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_pair_bytes(vec, out):
    passed = 0
    failed = 0
    codec = PairBytesCodec
    try:
        b = open(os.path.join(vec, "PairBytes.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairBytes.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairBytes mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairBytes.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairBytes.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairBytes json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairBytes.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairBytes.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairBytes unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "PairBytes.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "PairBytes.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL PairBytes gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_string_int32(vec, out):
    passed = 0
    failed = 0
    codec = DualStringInt32Codec
    try:
        b = open(os.path.join(vec, "DualStringInt32.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringInt32.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringInt32 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualStringInt32.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringInt32.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringInt32 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualStringInt32.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringInt32.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringInt32 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualStringInt32.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringInt32.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringInt32 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_string_boolean(vec, out):
    passed = 0
    failed = 0
    codec = DualStringBooleanCodec
    try:
        b = open(os.path.join(vec, "DualStringBoolean.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringBoolean.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringBoolean mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualStringBoolean.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringBoolean.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringBoolean json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualStringBoolean.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringBoolean.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringBoolean unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualStringBoolean.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringBoolean.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringBoolean gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_string_float64(vec, out):
    passed = 0
    failed = 0
    codec = DualStringFloat64Codec
    try:
        b = open(os.path.join(vec, "DualStringFloat64.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringFloat64.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringFloat64 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualStringFloat64.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringFloat64.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringFloat64 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualStringFloat64.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringFloat64.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringFloat64 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualStringFloat64.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringFloat64.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringFloat64 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_string_bytes(vec, out):
    passed = 0
    failed = 0
    codec = DualStringBytesCodec
    try:
        b = open(os.path.join(vec, "DualStringBytes.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringBytes.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringBytes mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualStringBytes.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringBytes.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringBytes json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualStringBytes.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringBytes.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringBytes unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualStringBytes.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringBytes.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringBytes gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_int32_boolean(vec, out):
    passed = 0
    failed = 0
    codec = DualInt32BooleanCodec
    try:
        b = open(os.path.join(vec, "DualInt32Boolean.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt32Boolean.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt32Boolean mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt32Boolean.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt32Boolean.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt32Boolean json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt32Boolean.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt32Boolean.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt32Boolean unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt32Boolean.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt32Boolean.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt32Boolean gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_int32_float64(vec, out):
    passed = 0
    failed = 0
    codec = DualInt32Float64Codec
    try:
        b = open(os.path.join(vec, "DualInt32Float64.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt32Float64.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt32Float64 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt32Float64.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt32Float64.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt32Float64 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt32Float64.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt32Float64.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt32Float64 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt32Float64.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt32Float64.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt32Float64 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_int32_int64(vec, out):
    passed = 0
    failed = 0
    codec = DualInt32Int64Codec
    try:
        b = open(os.path.join(vec, "DualInt32Int64.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt32Int64.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt32Int64 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt32Int64.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt32Int64.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt32Int64 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt32Int64.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt32Int64.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt32Int64 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt32Int64.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt32Int64.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt32Int64 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_int32_uint32(vec, out):
    passed = 0
    failed = 0
    codec = DualInt32Uint32Codec
    try:
        b = open(os.path.join(vec, "DualInt32Uint32.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt32Uint32.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt32Uint32 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt32Uint32.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt32Uint32.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt32Uint32 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt32Uint32.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt32Uint32.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt32Uint32 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt32Uint32.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt32Uint32.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt32Uint32 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_int64_uint64(vec, out):
    passed = 0
    failed = 0
    codec = DualInt64Uint64Codec
    try:
        b = open(os.path.join(vec, "DualInt64Uint64.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt64Uint64.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt64Uint64 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt64Uint64.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt64Uint64.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt64Uint64 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt64Uint64.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt64Uint64.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt64Uint64 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt64Uint64.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt64Uint64.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt64Uint64 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_float32_float64(vec, out):
    passed = 0
    failed = 0
    codec = DualFloat32Float64Codec
    try:
        b = open(os.path.join(vec, "DualFloat32Float64.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualFloat32Float64.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualFloat32Float64 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualFloat32Float64.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualFloat32Float64.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualFloat32Float64 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualFloat32Float64.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualFloat32Float64.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualFloat32Float64 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualFloat32Float64.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualFloat32Float64.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualFloat32Float64 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_float64_boolean(vec, out):
    passed = 0
    failed = 0
    codec = DualFloat64BooleanCodec
    try:
        b = open(os.path.join(vec, "DualFloat64Boolean.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualFloat64Boolean.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualFloat64Boolean mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualFloat64Boolean.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualFloat64Boolean.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualFloat64Boolean json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualFloat64Boolean.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualFloat64Boolean.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualFloat64Boolean unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualFloat64Boolean.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualFloat64Boolean.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualFloat64Boolean gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_float64_bytes(vec, out):
    passed = 0
    failed = 0
    codec = DualFloat64BytesCodec
    try:
        b = open(os.path.join(vec, "DualFloat64Bytes.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualFloat64Bytes.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualFloat64Bytes mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualFloat64Bytes.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualFloat64Bytes.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualFloat64Bytes json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualFloat64Bytes.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualFloat64Bytes.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualFloat64Bytes unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualFloat64Bytes.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualFloat64Bytes.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualFloat64Bytes gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_uint32_uint64(vec, out):
    passed = 0
    failed = 0
    codec = DualUint32Uint64Codec
    try:
        b = open(os.path.join(vec, "DualUint32Uint64.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualUint32Uint64.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualUint32Uint64 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualUint32Uint64.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualUint32Uint64.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualUint32Uint64 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualUint32Uint64.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualUint32Uint64.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualUint32Uint64 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualUint32Uint64.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualUint32Uint64.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualUint32Uint64 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_boolean_bytes(vec, out):
    passed = 0
    failed = 0
    codec = DualBooleanBytesCodec
    try:
        b = open(os.path.join(vec, "DualBooleanBytes.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualBooleanBytes.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualBooleanBytes mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualBooleanBytes.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualBooleanBytes.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualBooleanBytes json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualBooleanBytes.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualBooleanBytes.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualBooleanBytes unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualBooleanBytes.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualBooleanBytes.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualBooleanBytes gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_int8_uint8(vec, out):
    passed = 0
    failed = 0
    codec = DualInt8Uint8Codec
    try:
        b = open(os.path.join(vec, "DualInt8Uint8.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt8Uint8.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt8Uint8 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt8Uint8.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt8Uint8.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt8Uint8 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt8Uint8.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt8Uint8.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt8Uint8 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt8Uint8.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt8Uint8.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt8Uint8 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_int16_uint16(vec, out):
    passed = 0
    failed = 0
    codec = DualInt16Uint16Codec
    try:
        b = open(os.path.join(vec, "DualInt16Uint16.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt16Uint16.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt16Uint16 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt16Uint16.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt16Uint16.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt16Uint16 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt16Uint16.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt16Uint16.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt16Uint16 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt16Uint16.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt16Uint16.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt16Uint16 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_string_int64(vec, out):
    passed = 0
    failed = 0
    codec = DualStringInt64Codec
    try:
        b = open(os.path.join(vec, "DualStringInt64.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringInt64.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringInt64 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualStringInt64.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringInt64.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringInt64 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualStringInt64.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringInt64.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringInt64 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualStringInt64.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringInt64.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringInt64 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_string_uint64(vec, out):
    passed = 0
    failed = 0
    codec = DualStringUint64Codec
    try:
        b = open(os.path.join(vec, "DualStringUint64.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringUint64.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringUint64 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualStringUint64.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringUint64.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringUint64 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualStringUint64.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringUint64.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringUint64 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualStringUint64.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualStringUint64.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualStringUint64 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_int32_bytes(vec, out):
    passed = 0
    failed = 0
    codec = DualInt32BytesCodec
    try:
        b = open(os.path.join(vec, "DualInt32Bytes.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt32Bytes.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt32Bytes mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt32Bytes.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt32Bytes.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt32Bytes json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt32Bytes.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt32Bytes.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt32Bytes unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt32Bytes.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt32Bytes.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt32Bytes gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_float64_int32(vec, out):
    passed = 0
    failed = 0
    codec = DualFloat64Int32Codec
    try:
        b = open(os.path.join(vec, "DualFloat64Int32.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualFloat64Int32.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualFloat64Int32 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualFloat64Int32.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualFloat64Int32.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualFloat64Int32 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualFloat64Int32.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualFloat64Int32.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualFloat64Int32 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualFloat64Int32.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualFloat64Int32.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualFloat64Int32 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_boolean_int32(vec, out):
    passed = 0
    failed = 0
    codec = DualBooleanInt32Codec
    try:
        b = open(os.path.join(vec, "DualBooleanInt32.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualBooleanInt32.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualBooleanInt32 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualBooleanInt32.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualBooleanInt32.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualBooleanInt32 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualBooleanInt32.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualBooleanInt32.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualBooleanInt32 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualBooleanInt32.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualBooleanInt32.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualBooleanInt32 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_bytes_int64(vec, out):
    passed = 0
    failed = 0
    codec = DualBytesInt64Codec
    try:
        b = open(os.path.join(vec, "DualBytesInt64.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualBytesInt64.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualBytesInt64 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualBytesInt64.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualBytesInt64.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualBytesInt64 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualBytesInt64.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualBytesInt64.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualBytesInt64 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualBytesInt64.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualBytesInt64.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualBytesInt64 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_int8_float32(vec, out):
    passed = 0
    failed = 0
    codec = DualInt8Float32Codec
    try:
        b = open(os.path.join(vec, "DualInt8Float32.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt8Float32.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt8Float32 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt8Float32.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt8Float32.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt8Float32 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt8Float32.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt8Float32.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt8Float32 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt8Float32.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt8Float32.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt8Float32 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_uint8_int16(vec, out):
    passed = 0
    failed = 0
    codec = DualUint8Int16Codec
    try:
        b = open(os.path.join(vec, "DualUint8Int16.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualUint8Int16.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualUint8Int16 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualUint8Int16.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualUint8Int16.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualUint8Int16 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualUint8Int16.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualUint8Int16.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualUint8Int16 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualUint8Int16.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualUint8Int16.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualUint8Int16 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_int64_float64(vec, out):
    passed = 0
    failed = 0
    codec = DualInt64Float64Codec
    try:
        b = open(os.path.join(vec, "DualInt64Float64.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt64Float64.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt64Float64 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt64Float64.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt64Float64.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt64Float64 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt64Float64.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt64Float64.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt64Float64 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualInt64Float64.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualInt64Float64.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualInt64Float64 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_dual_uint64_string(vec, out):
    passed = 0
    failed = 0
    codec = DualUint64StringCodec
    try:
        b = open(os.path.join(vec, "DualUint64String.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualUint64String.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualUint64String mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualUint64String.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualUint64String.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualUint64String json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualUint64String.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualUint64String.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualUint64String unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DualUint64String.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DualUint64String.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DualUint64String gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_triple01(vec, out):
    passed = 0
    failed = 0
    codec = Triple01Codec
    try:
        b = open(os.path.join(vec, "Triple01.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple01.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple01 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple01.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple01.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple01 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple01.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple01.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple01 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple01.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple01.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple01 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_triple02(vec, out):
    passed = 0
    failed = 0
    codec = Triple02Codec
    try:
        b = open(os.path.join(vec, "Triple02.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple02.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple02 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple02.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple02.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple02 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple02.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple02.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple02 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple02.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple02.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple02 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_triple03(vec, out):
    passed = 0
    failed = 0
    codec = Triple03Codec
    try:
        b = open(os.path.join(vec, "Triple03.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple03.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple03 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple03.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple03.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple03 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple03.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple03.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple03 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple03.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple03.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple03 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_triple04(vec, out):
    passed = 0
    failed = 0
    codec = Triple04Codec
    try:
        b = open(os.path.join(vec, "Triple04.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple04.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple04 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple04.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple04.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple04 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple04.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple04.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple04 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple04.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple04.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple04 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_triple05(vec, out):
    passed = 0
    failed = 0
    codec = Triple05Codec
    try:
        b = open(os.path.join(vec, "Triple05.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple05.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple05 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple05.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple05.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple05 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple05.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple05.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple05 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple05.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple05.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple05 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_triple06(vec, out):
    passed = 0
    failed = 0
    codec = Triple06Codec
    try:
        b = open(os.path.join(vec, "Triple06.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple06.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple06 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple06.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple06.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple06 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple06.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple06.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple06 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple06.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple06.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple06 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_triple07(vec, out):
    passed = 0
    failed = 0
    codec = Triple07Codec
    try:
        b = open(os.path.join(vec, "Triple07.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple07.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple07 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple07.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple07.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple07 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple07.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple07.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple07 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple07.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple07.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple07 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_triple08(vec, out):
    passed = 0
    failed = 0
    codec = Triple08Codec
    try:
        b = open(os.path.join(vec, "Triple08.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple08.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple08 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple08.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple08.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple08 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple08.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple08.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple08 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple08.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple08.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple08 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_triple09(vec, out):
    passed = 0
    failed = 0
    codec = Triple09Codec
    try:
        b = open(os.path.join(vec, "Triple09.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple09.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple09 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple09.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple09.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple09 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple09.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple09.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple09 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple09.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple09.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple09 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_triple10(vec, out):
    passed = 0
    failed = 0
    codec = Triple10Codec
    try:
        b = open(os.path.join(vec, "Triple10.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple10.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple10 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple10.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple10.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple10 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple10.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple10.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple10 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple10.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple10.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple10 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_triple11(vec, out):
    passed = 0
    failed = 0
    codec = Triple11Codec
    try:
        b = open(os.path.join(vec, "Triple11.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple11.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple11 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple11.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple11.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple11 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple11.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple11.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple11 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple11.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple11.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple11 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_triple12(vec, out):
    passed = 0
    failed = 0
    codec = Triple12Codec
    try:
        b = open(os.path.join(vec, "Triple12.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple12.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple12 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple12.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple12.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple12 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple12.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple12.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple12 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple12.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple12.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple12 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_triple13(vec, out):
    passed = 0
    failed = 0
    codec = Triple13Codec
    try:
        b = open(os.path.join(vec, "Triple13.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple13.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple13 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple13.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple13.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple13 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple13.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple13.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple13 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple13.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple13.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple13 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_triple14(vec, out):
    passed = 0
    failed = 0
    codec = Triple14Codec
    try:
        b = open(os.path.join(vec, "Triple14.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple14.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple14 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple14.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple14.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple14 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple14.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple14.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple14 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple14.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple14.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple14 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_triple15(vec, out):
    passed = 0
    failed = 0
    codec = Triple15Codec
    try:
        b = open(os.path.join(vec, "Triple15.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple15.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple15 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple15.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple15.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple15 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple15.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple15.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple15 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Triple15.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Triple15.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Triple15 gron: " + str(e))
        failed += 1
    return passed, failed
def run_AllTypes_Pairs():
    passed = 0
    failed = 0
    vec = os.environ["VEC_DIR"]
    out = os.environ["OUT_DIR"]
    os.makedirs(out, exist_ok=True)

    # Object tests
    p, f = test_model_pair_string(vec, out); passed += p; failed += f
    p, f = test_model_pair_boolean(vec, out); passed += p; failed += f
    p, f = test_model_pair_int8(vec, out); passed += p; failed += f
    p, f = test_model_pair_int16(vec, out); passed += p; failed += f
    p, f = test_model_pair_int32(vec, out); passed += p; failed += f
    p, f = test_model_pair_int64(vec, out); passed += p; failed += f
    p, f = test_model_pair_uint8(vec, out); passed += p; failed += f
    p, f = test_model_pair_uint16(vec, out); passed += p; failed += f
    p, f = test_model_pair_uint32(vec, out); passed += p; failed += f
    p, f = test_model_pair_uint64(vec, out); passed += p; failed += f
    p, f = test_model_pair_float32(vec, out); passed += p; failed += f
    p, f = test_model_pair_float64(vec, out); passed += p; failed += f
    p, f = test_model_pair_bytes(vec, out); passed += p; failed += f
    p, f = test_model_dual_string_int32(vec, out); passed += p; failed += f
    p, f = test_model_dual_string_boolean(vec, out); passed += p; failed += f
    p, f = test_model_dual_string_float64(vec, out); passed += p; failed += f
    p, f = test_model_dual_string_bytes(vec, out); passed += p; failed += f
    p, f = test_model_dual_int32_boolean(vec, out); passed += p; failed += f
    p, f = test_model_dual_int32_float64(vec, out); passed += p; failed += f
    p, f = test_model_dual_int32_int64(vec, out); passed += p; failed += f
    p, f = test_model_dual_int32_uint32(vec, out); passed += p; failed += f
    p, f = test_model_dual_int64_uint64(vec, out); passed += p; failed += f
    p, f = test_model_dual_float32_float64(vec, out); passed += p; failed += f
    p, f = test_model_dual_float64_boolean(vec, out); passed += p; failed += f
    p, f = test_model_dual_float64_bytes(vec, out); passed += p; failed += f
    p, f = test_model_dual_uint32_uint64(vec, out); passed += p; failed += f
    p, f = test_model_dual_boolean_bytes(vec, out); passed += p; failed += f
    p, f = test_model_dual_int8_uint8(vec, out); passed += p; failed += f
    p, f = test_model_dual_int16_uint16(vec, out); passed += p; failed += f
    p, f = test_model_dual_string_int64(vec, out); passed += p; failed += f
    p, f = test_model_dual_string_uint64(vec, out); passed += p; failed += f
    p, f = test_model_dual_int32_bytes(vec, out); passed += p; failed += f
    p, f = test_model_dual_float64_int32(vec, out); passed += p; failed += f
    p, f = test_model_dual_boolean_int32(vec, out); passed += p; failed += f
    p, f = test_model_dual_bytes_int64(vec, out); passed += p; failed += f
    p, f = test_model_dual_int8_float32(vec, out); passed += p; failed += f
    p, f = test_model_dual_uint8_int16(vec, out); passed += p; failed += f
    p, f = test_model_dual_int64_float64(vec, out); passed += p; failed += f
    p, f = test_model_dual_uint64_string(vec, out); passed += p; failed += f
    p, f = test_model_triple01(vec, out); passed += p; failed += f
    p, f = test_model_triple02(vec, out); passed += p; failed += f
    p, f = test_model_triple03(vec, out); passed += p; failed += f
    p, f = test_model_triple04(vec, out); passed += p; failed += f
    p, f = test_model_triple05(vec, out); passed += p; failed += f
    p, f = test_model_triple06(vec, out); passed += p; failed += f
    p, f = test_model_triple07(vec, out); passed += p; failed += f
    p, f = test_model_triple08(vec, out); passed += p; failed += f
    p, f = test_model_triple09(vec, out); passed += p; failed += f
    p, f = test_model_triple10(vec, out); passed += p; failed += f
    p, f = test_model_triple11(vec, out); passed += p; failed += f
    p, f = test_model_triple12(vec, out); passed += p; failed += f
    p, f = test_model_triple13(vec, out); passed += p; failed += f
    p, f = test_model_triple14(vec, out); passed += p; failed += f
    p, f = test_model_triple15(vec, out); passed += p; failed += f
    return passed, failed
