# Generated by generate_emit_runner.mjs. DO NOT EDIT.
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from generated import *
from specodec.msgpack_reader import MsgPackReader
from specodec.msgpack_writer import MsgPackWriter
from specodec.json_reader import JsonReader
from specodec.json_writer import JsonWriter
from specodec.gron_reader import GronReader
from specodec.gron_writer import GronWriter


def test_model_five01(vec, out):
    passed = 0
    failed = 0
    codec = Five01Codec
    try:
        b = open(os.path.join(vec, "Five01.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five01.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five01 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five01.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five01.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five01 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five01.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five01.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five01 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five01.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five01.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five01 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_five02(vec, out):
    passed = 0
    failed = 0
    codec = Five02Codec
    try:
        b = open(os.path.join(vec, "Five02.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five02.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five02 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five02.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five02.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five02 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five02.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five02.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five02 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five02.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five02.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five02 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_five03(vec, out):
    passed = 0
    failed = 0
    codec = Five03Codec
    try:
        b = open(os.path.join(vec, "Five03.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five03.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five03 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five03.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five03.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five03 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five03.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five03.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five03 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five03.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five03.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five03 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_five04(vec, out):
    passed = 0
    failed = 0
    codec = Five04Codec
    try:
        b = open(os.path.join(vec, "Five04.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five04.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five04 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five04.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five04.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five04 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five04.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five04.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five04 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five04.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five04.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five04 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_five05(vec, out):
    passed = 0
    failed = 0
    codec = Five05Codec
    try:
        b = open(os.path.join(vec, "Five05.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five05.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five05 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five05.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five05.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five05 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five05.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five05.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five05 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five05.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five05.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five05 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_five06(vec, out):
    passed = 0
    failed = 0
    codec = Five06Codec
    try:
        b = open(os.path.join(vec, "Five06.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five06.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five06 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five06.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five06.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five06 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five06.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five06.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five06 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five06.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five06.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five06 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_five07(vec, out):
    passed = 0
    failed = 0
    codec = Five07Codec
    try:
        b = open(os.path.join(vec, "Five07.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five07.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five07 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five07.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five07.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five07 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five07.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five07.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five07 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five07.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five07.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five07 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_five08(vec, out):
    passed = 0
    failed = 0
    codec = Five08Codec
    try:
        b = open(os.path.join(vec, "Five08.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five08.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five08 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five08.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five08.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five08 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five08.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five08.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five08 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five08.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five08.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five08 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_five09(vec, out):
    passed = 0
    failed = 0
    codec = Five09Codec
    try:
        b = open(os.path.join(vec, "Five09.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five09.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five09 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five09.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five09.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five09 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five09.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five09.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five09 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five09.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five09.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five09 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_five10(vec, out):
    passed = 0
    failed = 0
    codec = Five10Codec
    try:
        b = open(os.path.join(vec, "Five10.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five10.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five10 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five10.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five10.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five10 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five10.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five10.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five10 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Five10.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Five10.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Five10 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_ten01(vec, out):
    passed = 0
    failed = 0
    codec = Ten01Codec
    try:
        b = open(os.path.join(vec, "Ten01.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ten01.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ten01 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Ten01.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ten01.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ten01 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Ten01.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ten01.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ten01 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Ten01.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ten01.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ten01 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_ten02(vec, out):
    passed = 0
    failed = 0
    codec = Ten02Codec
    try:
        b = open(os.path.join(vec, "Ten02.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ten02.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ten02 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Ten02.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ten02.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ten02 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Ten02.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ten02.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ten02 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Ten02.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ten02.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ten02 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_ten03(vec, out):
    passed = 0
    failed = 0
    codec = Ten03Codec
    try:
        b = open(os.path.join(vec, "Ten03.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ten03.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ten03 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Ten03.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ten03.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ten03 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Ten03.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ten03.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ten03 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Ten03.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ten03.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ten03 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_ten04(vec, out):
    passed = 0
    failed = 0
    codec = Ten04Codec
    try:
        b = open(os.path.join(vec, "Ten04.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ten04.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ten04 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Ten04.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ten04.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ten04 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Ten04.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ten04.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ten04 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Ten04.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ten04.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ten04 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_ten05(vec, out):
    passed = 0
    failed = 0
    codec = Ten05Codec
    try:
        b = open(os.path.join(vec, "Ten05.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ten05.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ten05 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Ten05.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ten05.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ten05 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Ten05.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ten05.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ten05 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Ten05.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Ten05.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Ten05 gron: " + str(e))
        failed += 1
    return passed, failed
def run_AllTypes_Many():
    passed = 0
    failed = 0
    vec = os.environ["VEC_DIR"]
    out = os.environ["OUT_DIR"]
    os.makedirs(out, exist_ok=True)

    # Object tests
    p, f = test_model_five01(vec, out); passed += p; failed += f
    p, f = test_model_five02(vec, out); passed += p; failed += f
    p, f = test_model_five03(vec, out); passed += p; failed += f
    p, f = test_model_five04(vec, out); passed += p; failed += f
    p, f = test_model_five05(vec, out); passed += p; failed += f
    p, f = test_model_five06(vec, out); passed += p; failed += f
    p, f = test_model_five07(vec, out); passed += p; failed += f
    p, f = test_model_five08(vec, out); passed += p; failed += f
    p, f = test_model_five09(vec, out); passed += p; failed += f
    p, f = test_model_five10(vec, out); passed += p; failed += f
    p, f = test_model_ten01(vec, out); passed += p; failed += f
    p, f = test_model_ten02(vec, out); passed += p; failed += f
    p, f = test_model_ten03(vec, out); passed += p; failed += f
    p, f = test_model_ten04(vec, out); passed += p; failed += f
    p, f = test_model_ten05(vec, out); passed += p; failed += f
    return passed, failed
