# Generated by generate_emit_runner.mjs. DO NOT EDIT.
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from generated import *
from specodec.msgpack_reader import MsgPackReader
from specodec.msgpack_writer import MsgPackWriter
from specodec.json_reader import JsonReader
from specodec.json_writer import JsonWriter
from specodec.gron_reader import GronReader
from specodec.gron_writer import GronWriter


def test_model_wide20(vec, out):
    passed = 0
    failed = 0
    codec = Wide20Codec
    try:
        b = open(os.path.join(vec, "Wide20.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Wide20.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Wide20 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Wide20.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Wide20.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Wide20 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Wide20.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Wide20.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Wide20 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Wide20.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Wide20.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Wide20 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_wide25(vec, out):
    passed = 0
    failed = 0
    codec = Wide25Codec
    try:
        b = open(os.path.join(vec, "Wide25.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Wide25.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Wide25 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Wide25.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Wide25.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Wide25 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Wide25.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Wide25.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Wide25 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Wide25.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Wide25.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Wide25 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_wide30(vec, out):
    passed = 0
    failed = 0
    codec = Wide30Codec
    try:
        b = open(os.path.join(vec, "Wide30.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Wide30.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Wide30 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Wide30.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Wide30.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Wide30 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Wide30.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Wide30.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Wide30 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Wide30.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Wide30.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Wide30 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_wide35(vec, out):
    passed = 0
    failed = 0
    codec = Wide35Codec
    try:
        b = open(os.path.join(vec, "Wide35.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Wide35.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Wide35 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Wide35.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Wide35.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Wide35 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Wide35.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Wide35.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Wide35 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Wide35.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Wide35.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Wide35 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_wide40(vec, out):
    passed = 0
    failed = 0
    codec = Wide40Codec
    try:
        b = open(os.path.join(vec, "Wide40.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Wide40.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Wide40 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Wide40.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Wide40.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Wide40 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Wide40.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Wide40.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Wide40 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Wide40.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Wide40.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Wide40 gron: " + str(e))
        failed += 1
    return passed, failed
def run_AllTypes_Wide():
    passed = 0
    failed = 0
    vec = os.environ["VEC_DIR"]
    out = os.environ["OUT_DIR"]
    os.makedirs(out, exist_ok=True)

    # Object tests
    p, f = test_model_wide20(vec, out); passed += p; failed += f
    p, f = test_model_wide25(vec, out); passed += p; failed += f
    p, f = test_model_wide30(vec, out); passed += p; failed += f
    p, f = test_model_wide35(vec, out); passed += p; failed += f
    p, f = test_model_wide40(vec, out); passed += p; failed += f
    return passed, failed
