# Generated by generate_emit_runner.mjs. DO NOT EDIT.
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from generated import *
from specodec.msgpack_reader import MsgPackReader
from specodec.msgpack_writer import MsgPackWriter
from specodec.json_reader import JsonReader
from specodec.json_writer import JsonWriter
from specodec.gron_reader import GronReader
from specodec.gron_writer import GronWriter


def test_model_opt_inner(vec, out):
    passed = 0
    failed = 0
    codec = OptInnerCodec
    try:
        b = open(os.path.join(vec, "OptInner.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptInner.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptInner mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptInner.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptInner.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptInner json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptInner.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptInner.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptInner unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptInner.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptInner.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptInner gron: " + str(e))
        failed += 1
    return passed, failed
def run_AllTypes():
    passed = 0
    failed = 0
    vec = os.environ["VEC_DIR"]
    out = os.environ["OUT_DIR"]
    os.makedirs(out, exist_ok=True)

    # Object tests
    p, f = test_model_opt_inner(vec, out); passed += p; failed += f
    return passed, failed
