# Generated by generate_emit_runner.mjs. DO NOT EDIT.
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from generated import *
from specodec.msgpack_reader import MsgPackReader
from specodec.msgpack_writer import MsgPackWriter
from specodec.json_reader import JsonReader
from specodec.json_writer import JsonWriter
from specodec.gron_reader import GronReader
from specodec.gron_writer import GronWriter


def test_model_union_field_holder(vec, out):
    passed = 0
    failed = 0
    codec = UnionFieldHolderCodec
    try:
        b = open(os.path.join(vec, "UnionFieldHolder.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "UnionFieldHolder.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL UnionFieldHolder mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "UnionFieldHolder.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "UnionFieldHolder.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL UnionFieldHolder json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "UnionFieldHolder.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "UnionFieldHolder.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL UnionFieldHolder unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "UnionFieldHolder.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "UnionFieldHolder.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL UnionFieldHolder gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_union_field_holder(vec, out):
    passed = 0
    failed = 0
    codec = OptUnionFieldHolderCodec
    try:
        b = open(os.path.join(vec, "OptUnionFieldHolder.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptUnionFieldHolder.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptUnionFieldHolder mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptUnionFieldHolder.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptUnionFieldHolder.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptUnionFieldHolder json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptUnionFieldHolder.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptUnionFieldHolder.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptUnionFieldHolder unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptUnionFieldHolder.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptUnionFieldHolder.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptUnionFieldHolder gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_union_array_holder(vec, out):
    passed = 0
    failed = 0
    codec = UnionArrayHolderCodec
    try:
        b = open(os.path.join(vec, "UnionArrayHolder.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "UnionArrayHolder.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL UnionArrayHolder mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "UnionArrayHolder.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "UnionArrayHolder.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL UnionArrayHolder json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "UnionArrayHolder.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "UnionArrayHolder.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL UnionArrayHolder unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "UnionArrayHolder.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "UnionArrayHolder.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL UnionArrayHolder gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_union_mixed_holder(vec, out):
    passed = 0
    failed = 0
    codec = UnionMixedHolderCodec
    try:
        b = open(os.path.join(vec, "UnionMixedHolder.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "UnionMixedHolder.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL UnionMixedHolder mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "UnionMixedHolder.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "UnionMixedHolder.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL UnionMixedHolder json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "UnionMixedHolder.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "UnionMixedHolder.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL UnionMixedHolder unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "UnionMixedHolder.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "UnionMixedHolder.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL UnionMixedHolder gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_union_scalar_holder(vec, out):
    passed = 0
    failed = 0
    codec = UnionScalarHolderCodec
    try:
        b = open(os.path.join(vec, "UnionScalarHolder.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "UnionScalarHolder.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL UnionScalarHolder mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "UnionScalarHolder.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "UnionScalarHolder.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL UnionScalarHolder json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "UnionScalarHolder.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "UnionScalarHolder.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL UnionScalarHolder unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "UnionScalarHolder.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "UnionScalarHolder.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL UnionScalarHolder gron: " + str(e))
        failed += 1
    return passed, failed
def run_AllTypes_Unions():
    passed = 0
    failed = 0
    vec = os.environ["VEC_DIR"]
    out = os.environ["OUT_DIR"]
    os.makedirs(out, exist_ok=True)

    # Object tests
    p, f = test_model_union_field_holder(vec, out); passed += p; failed += f
    p, f = test_model_opt_union_field_holder(vec, out); passed += p; failed += f
    p, f = test_model_union_array_holder(vec, out); passed += p; failed += f
    p, f = test_model_union_mixed_holder(vec, out); passed += p; failed += f
    p, f = test_model_union_scalar_holder(vec, out); passed += p; failed += f
    return passed, failed
