# Generated by generate_emit_runner.mjs. DO NOT EDIT.
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from generated import *
from specodec.msgpack_reader import MsgPackReader
from specodec.msgpack_writer import MsgPackWriter
from specodec.json_reader import JsonReader
from specodec.json_writer import JsonWriter
from specodec.gron_reader import GronReader
from specodec.gron_writer import GronWriter


def test_model_opt_arr1(vec, out):
    passed = 0
    failed = 0
    codec = OptArr1Codec
    try:
        b = open(os.path.join(vec, "OptArr1.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptArr1.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptArr1 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptArr1.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptArr1.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptArr1 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptArr1.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptArr1.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptArr1 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptArr1.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptArr1.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptArr1 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_arr2(vec, out):
    passed = 0
    failed = 0
    codec = OptArr2Codec
    try:
        b = open(os.path.join(vec, "OptArr2.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptArr2.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptArr2 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptArr2.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptArr2.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptArr2 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptArr2.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptArr2.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptArr2 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptArr2.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptArr2.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptArr2 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_arr3(vec, out):
    passed = 0
    failed = 0
    codec = OptArr3Codec
    try:
        b = open(os.path.join(vec, "OptArr3.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptArr3.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptArr3 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptArr3.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptArr3.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptArr3 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptArr3.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptArr3.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptArr3 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptArr3.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptArr3.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptArr3 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_arr4(vec, out):
    passed = 0
    failed = 0
    codec = OptArr4Codec
    try:
        b = open(os.path.join(vec, "OptArr4.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptArr4.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptArr4 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptArr4.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptArr4.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptArr4 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptArr4.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptArr4.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptArr4 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptArr4.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptArr4.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptArr4 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_arr5(vec, out):
    passed = 0
    failed = 0
    codec = OptArr5Codec
    try:
        b = open(os.path.join(vec, "OptArr5.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptArr5.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptArr5 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptArr5.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptArr5.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptArr5 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptArr5.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptArr5.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptArr5 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptArr5.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptArr5.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptArr5 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_nest_opt1(vec, out):
    passed = 0
    failed = 0
    codec = NestOpt1Codec
    try:
        b = open(os.path.join(vec, "NestOpt1.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOpt1.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOpt1 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOpt1.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOpt1.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOpt1 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOpt1.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOpt1.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOpt1 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOpt1.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOpt1.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOpt1 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_nest_opt2(vec, out):
    passed = 0
    failed = 0
    codec = NestOpt2Codec
    try:
        b = open(os.path.join(vec, "NestOpt2.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOpt2.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOpt2 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOpt2.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOpt2.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOpt2 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOpt2.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOpt2.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOpt2 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOpt2.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOpt2.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOpt2 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_nest_opt3(vec, out):
    passed = 0
    failed = 0
    codec = NestOpt3Codec
    try:
        b = open(os.path.join(vec, "NestOpt3.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOpt3.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOpt3 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOpt3.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOpt3.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOpt3 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOpt3.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOpt3.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOpt3 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOpt3.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOpt3.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOpt3 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_nest_opt4(vec, out):
    passed = 0
    failed = 0
    codec = NestOpt4Codec
    try:
        b = open(os.path.join(vec, "NestOpt4.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOpt4.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOpt4 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOpt4.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOpt4.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOpt4 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOpt4.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOpt4.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOpt4 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOpt4.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOpt4.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOpt4 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_nest_opt5(vec, out):
    passed = 0
    failed = 0
    codec = NestOpt5Codec
    try:
        b = open(os.path.join(vec, "NestOpt5.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOpt5.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOpt5 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOpt5.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOpt5.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOpt5 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOpt5.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOpt5.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOpt5 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOpt5.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOpt5.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOpt5 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_nest_opt_inner1(vec, out):
    passed = 0
    failed = 0
    codec = NestOptInner1Codec
    try:
        b = open(os.path.join(vec, "NestOptInner1.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOptInner1.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOptInner1 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOptInner1.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOptInner1.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOptInner1 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOptInner1.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOptInner1.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOptInner1 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOptInner1.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOptInner1.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOptInner1 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_nest_opt_inner2(vec, out):
    passed = 0
    failed = 0
    codec = NestOptInner2Codec
    try:
        b = open(os.path.join(vec, "NestOptInner2.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOptInner2.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOptInner2 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOptInner2.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOptInner2.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOptInner2 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOptInner2.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOptInner2.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOptInner2 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOptInner2.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOptInner2.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOptInner2 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_nest_opt_inner3(vec, out):
    passed = 0
    failed = 0
    codec = NestOptInner3Codec
    try:
        b = open(os.path.join(vec, "NestOptInner3.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOptInner3.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOptInner3 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOptInner3.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOptInner3.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOptInner3 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOptInner3.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOptInner3.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOptInner3 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestOptInner3.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestOptInner3.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestOptInner3 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_deep_nest1(vec, out):
    passed = 0
    failed = 0
    codec = DeepNest1Codec
    try:
        b = open(os.path.join(vec, "DeepNest1.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest1.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest1 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DeepNest1.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest1.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest1 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DeepNest1.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest1.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest1 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DeepNest1.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest1.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest1 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_deep_nest2(vec, out):
    passed = 0
    failed = 0
    codec = DeepNest2Codec
    try:
        b = open(os.path.join(vec, "DeepNest2.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest2.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest2 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DeepNest2.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest2.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest2 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DeepNest2.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest2.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest2 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DeepNest2.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest2.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest2 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_deep_nest3(vec, out):
    passed = 0
    failed = 0
    codec = DeepNest3Codec
    try:
        b = open(os.path.join(vec, "DeepNest3.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest3.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest3 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DeepNest3.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest3.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest3 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DeepNest3.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest3.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest3 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DeepNest3.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest3.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest3 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_deep_nest4(vec, out):
    passed = 0
    failed = 0
    codec = DeepNest4Codec
    try:
        b = open(os.path.join(vec, "DeepNest4.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest4.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest4 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DeepNest4.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest4.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest4 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DeepNest4.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest4.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest4 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DeepNest4.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest4.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest4 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_deep_nest5(vec, out):
    passed = 0
    failed = 0
    codec = DeepNest5Codec
    try:
        b = open(os.path.join(vec, "DeepNest5.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest5.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest5 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DeepNest5.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest5.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest5 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DeepNest5.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest5.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest5 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DeepNest5.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest5.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest5 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_deep_nest6(vec, out):
    passed = 0
    failed = 0
    codec = DeepNest6Codec
    try:
        b = open(os.path.join(vec, "DeepNest6.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest6.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest6 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DeepNest6.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest6.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest6 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DeepNest6.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest6.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest6 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DeepNest6.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest6.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest6 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_deep_nest7(vec, out):
    passed = 0
    failed = 0
    codec = DeepNest7Codec
    try:
        b = open(os.path.join(vec, "DeepNest7.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest7.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest7 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DeepNest7.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest7.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest7 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DeepNest7.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest7.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest7 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "DeepNest7.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "DeepNest7.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL DeepNest7 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_timestamp_entry(vec, out):
    passed = 0
    failed = 0
    codec = TimestampEntryCodec
    try:
        b = open(os.path.join(vec, "TimestampEntry.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "TimestampEntry.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL TimestampEntry mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "TimestampEntry.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "TimestampEntry.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL TimestampEntry json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "TimestampEntry.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "TimestampEntry.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL TimestampEntry unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "TimestampEntry.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "TimestampEntry.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL TimestampEntry gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_config_entry(vec, out):
    passed = 0
    failed = 0
    codec = ConfigEntryCodec
    try:
        b = open(os.path.join(vec, "ConfigEntry.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ConfigEntry.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ConfigEntry mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ConfigEntry.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ConfigEntry.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ConfigEntry json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ConfigEntry.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ConfigEntry.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ConfigEntry unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ConfigEntry.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ConfigEntry.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ConfigEntry gron: " + str(e))
        failed += 1
    return passed, failed
def run_AllTypes_Extra():
    passed = 0
    failed = 0
    vec = os.environ["VEC_DIR"]
    out = os.environ["OUT_DIR"]
    os.makedirs(out, exist_ok=True)

    # Object tests
    p, f = test_model_opt_arr1(vec, out); passed += p; failed += f
    p, f = test_model_opt_arr2(vec, out); passed += p; failed += f
    p, f = test_model_opt_arr3(vec, out); passed += p; failed += f
    p, f = test_model_opt_arr4(vec, out); passed += p; failed += f
    p, f = test_model_opt_arr5(vec, out); passed += p; failed += f
    p, f = test_model_nest_opt1(vec, out); passed += p; failed += f
    p, f = test_model_nest_opt2(vec, out); passed += p; failed += f
    p, f = test_model_nest_opt3(vec, out); passed += p; failed += f
    p, f = test_model_nest_opt4(vec, out); passed += p; failed += f
    p, f = test_model_nest_opt5(vec, out); passed += p; failed += f
    p, f = test_model_nest_opt_inner1(vec, out); passed += p; failed += f
    p, f = test_model_nest_opt_inner2(vec, out); passed += p; failed += f
    p, f = test_model_nest_opt_inner3(vec, out); passed += p; failed += f
    p, f = test_model_deep_nest1(vec, out); passed += p; failed += f
    p, f = test_model_deep_nest2(vec, out); passed += p; failed += f
    p, f = test_model_deep_nest3(vec, out); passed += p; failed += f
    p, f = test_model_deep_nest4(vec, out); passed += p; failed += f
    p, f = test_model_deep_nest5(vec, out); passed += p; failed += f
    p, f = test_model_deep_nest6(vec, out); passed += p; failed += f
    p, f = test_model_deep_nest7(vec, out); passed += p; failed += f
    p, f = test_model_timestamp_entry(vec, out); passed += p; failed += f
    p, f = test_model_config_entry(vec, out); passed += p; failed += f
    return passed, failed
