# Generated by generate_emit_runner.mjs. DO NOT EDIT.
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from generated import *
from specodec.msgpack_reader import MsgPackReader
from specodec.msgpack_writer import MsgPackWriter
from specodec.json_reader import JsonReader
from specodec.json_writer import JsonWriter
from specodec.gron_reader import GronReader
from specodec.gron_writer import GronWriter


def test_model_model_arr1(vec, out):
    passed = 0
    failed = 0
    codec = ModelArr1Codec
    try:
        b = open(os.path.join(vec, "ModelArr1.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ModelArr1.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ModelArr1 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ModelArr1.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ModelArr1.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ModelArr1 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ModelArr1.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ModelArr1.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ModelArr1 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ModelArr1.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ModelArr1.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ModelArr1 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_model_arr2(vec, out):
    passed = 0
    failed = 0
    codec = ModelArr2Codec
    try:
        b = open(os.path.join(vec, "ModelArr2.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ModelArr2.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ModelArr2 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ModelArr2.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ModelArr2.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ModelArr2 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ModelArr2.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ModelArr2.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ModelArr2 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ModelArr2.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ModelArr2.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ModelArr2 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_model_arr3(vec, out):
    passed = 0
    failed = 0
    codec = ModelArr3Codec
    try:
        b = open(os.path.join(vec, "ModelArr3.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ModelArr3.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ModelArr3 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ModelArr3.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ModelArr3.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ModelArr3 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ModelArr3.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ModelArr3.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ModelArr3 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ModelArr3.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ModelArr3.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ModelArr3 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_model_arr4(vec, out):
    passed = 0
    failed = 0
    codec = ModelArr4Codec
    try:
        b = open(os.path.join(vec, "ModelArr4.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ModelArr4.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ModelArr4 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ModelArr4.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ModelArr4.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ModelArr4 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ModelArr4.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ModelArr4.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ModelArr4 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ModelArr4.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ModelArr4.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ModelArr4 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_model_arr5(vec, out):
    passed = 0
    failed = 0
    codec = ModelArr5Codec
    try:
        b = open(os.path.join(vec, "ModelArr5.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ModelArr5.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ModelArr5 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ModelArr5.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ModelArr5.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ModelArr5 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ModelArr5.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ModelArr5.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ModelArr5 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "ModelArr5.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "ModelArr5.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL ModelArr5 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_mix01(vec, out):
    passed = 0
    failed = 0
    codec = Mix01Codec
    try:
        b = open(os.path.join(vec, "Mix01.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix01.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix01 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix01.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix01.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix01 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix01.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix01.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix01 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix01.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix01.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix01 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_mix02(vec, out):
    passed = 0
    failed = 0
    codec = Mix02Codec
    try:
        b = open(os.path.join(vec, "Mix02.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix02.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix02 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix02.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix02.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix02 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix02.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix02.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix02 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix02.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix02.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix02 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_mix03(vec, out):
    passed = 0
    failed = 0
    codec = Mix03Codec
    try:
        b = open(os.path.join(vec, "Mix03.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix03.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix03 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix03.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix03.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix03 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix03.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix03.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix03 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix03.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix03.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix03 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_mix04(vec, out):
    passed = 0
    failed = 0
    codec = Mix04Codec
    try:
        b = open(os.path.join(vec, "Mix04.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix04.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix04 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix04.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix04.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix04 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix04.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix04.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix04 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix04.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix04.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix04 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_mix05(vec, out):
    passed = 0
    failed = 0
    codec = Mix05Codec
    try:
        b = open(os.path.join(vec, "Mix05.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix05.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix05 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix05.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix05.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix05 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix05.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix05.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix05 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix05.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix05.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix05 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_mix06(vec, out):
    passed = 0
    failed = 0
    codec = Mix06Codec
    try:
        b = open(os.path.join(vec, "Mix06.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix06.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix06 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix06.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix06.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix06 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix06.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix06.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix06 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix06.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix06.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix06 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_mix07(vec, out):
    passed = 0
    failed = 0
    codec = Mix07Codec
    try:
        b = open(os.path.join(vec, "Mix07.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix07.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix07 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix07.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix07.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix07 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix07.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix07.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix07 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix07.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix07.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix07 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_mix08(vec, out):
    passed = 0
    failed = 0
    codec = Mix08Codec
    try:
        b = open(os.path.join(vec, "Mix08.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix08.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix08 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix08.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix08.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix08 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix08.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix08.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix08 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix08.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix08.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix08 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_mix09(vec, out):
    passed = 0
    failed = 0
    codec = Mix09Codec
    try:
        b = open(os.path.join(vec, "Mix09.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix09.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix09 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix09.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix09.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix09 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix09.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix09.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix09 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix09.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix09.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix09 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_mix10(vec, out):
    passed = 0
    failed = 0
    codec = Mix10Codec
    try:
        b = open(os.path.join(vec, "Mix10.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix10.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix10 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix10.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix10.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix10 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix10.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix10.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix10 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix10.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix10.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix10 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_mix11(vec, out):
    passed = 0
    failed = 0
    codec = Mix11Codec
    try:
        b = open(os.path.join(vec, "Mix11.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix11.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix11 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix11.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix11.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix11 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix11.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix11.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix11 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix11.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix11.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix11 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_mix12(vec, out):
    passed = 0
    failed = 0
    codec = Mix12Codec
    try:
        b = open(os.path.join(vec, "Mix12.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix12.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix12 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix12.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix12.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix12 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix12.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix12.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix12 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix12.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix12.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix12 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_mix13(vec, out):
    passed = 0
    failed = 0
    codec = Mix13Codec
    try:
        b = open(os.path.join(vec, "Mix13.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix13.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix13 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix13.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix13.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix13 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix13.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix13.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix13 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix13.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix13.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix13 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_mix14(vec, out):
    passed = 0
    failed = 0
    codec = Mix14Codec
    try:
        b = open(os.path.join(vec, "Mix14.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix14.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix14 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix14.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix14.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix14 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix14.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix14.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix14 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix14.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix14.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix14 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_mix15(vec, out):
    passed = 0
    failed = 0
    codec = Mix15Codec
    try:
        b = open(os.path.join(vec, "Mix15.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix15.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix15 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix15.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix15.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix15 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix15.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix15.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix15 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "Mix15.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "Mix15.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL Mix15 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_all_opt1(vec, out):
    passed = 0
    failed = 0
    codec = AllOpt1Codec
    try:
        b = open(os.path.join(vec, "AllOpt1.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "AllOpt1.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL AllOpt1 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "AllOpt1.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "AllOpt1.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL AllOpt1 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "AllOpt1.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "AllOpt1.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL AllOpt1 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "AllOpt1.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "AllOpt1.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL AllOpt1 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_all_opt2(vec, out):
    passed = 0
    failed = 0
    codec = AllOpt2Codec
    try:
        b = open(os.path.join(vec, "AllOpt2.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "AllOpt2.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL AllOpt2 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "AllOpt2.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "AllOpt2.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL AllOpt2 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "AllOpt2.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "AllOpt2.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL AllOpt2 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "AllOpt2.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "AllOpt2.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL AllOpt2 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_all_opt3(vec, out):
    passed = 0
    failed = 0
    codec = AllOpt3Codec
    try:
        b = open(os.path.join(vec, "AllOpt3.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "AllOpt3.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL AllOpt3 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "AllOpt3.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "AllOpt3.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL AllOpt3 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "AllOpt3.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "AllOpt3.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL AllOpt3 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "AllOpt3.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "AllOpt3.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL AllOpt3 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_all_opt4(vec, out):
    passed = 0
    failed = 0
    codec = AllOpt4Codec
    try:
        b = open(os.path.join(vec, "AllOpt4.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "AllOpt4.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL AllOpt4 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "AllOpt4.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "AllOpt4.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL AllOpt4 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "AllOpt4.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "AllOpt4.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL AllOpt4 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "AllOpt4.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "AllOpt4.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL AllOpt4 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_all_opt5(vec, out):
    passed = 0
    failed = 0
    codec = AllOpt5Codec
    try:
        b = open(os.path.join(vec, "AllOpt5.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "AllOpt5.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL AllOpt5 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "AllOpt5.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "AllOpt5.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL AllOpt5 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "AllOpt5.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "AllOpt5.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL AllOpt5 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "AllOpt5.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "AllOpt5.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL AllOpt5 gron: " + str(e))
        failed += 1
    return passed, failed
def run_AllTypes_Mixed():
    passed = 0
    failed = 0
    vec = os.environ["VEC_DIR"]
    out = os.environ["OUT_DIR"]
    os.makedirs(out, exist_ok=True)

    # Object tests
    p, f = test_model_model_arr1(vec, out); passed += p; failed += f
    p, f = test_model_model_arr2(vec, out); passed += p; failed += f
    p, f = test_model_model_arr3(vec, out); passed += p; failed += f
    p, f = test_model_model_arr4(vec, out); passed += p; failed += f
    p, f = test_model_model_arr5(vec, out); passed += p; failed += f
    p, f = test_model_mix01(vec, out); passed += p; failed += f
    p, f = test_model_mix02(vec, out); passed += p; failed += f
    p, f = test_model_mix03(vec, out); passed += p; failed += f
    p, f = test_model_mix04(vec, out); passed += p; failed += f
    p, f = test_model_mix05(vec, out); passed += p; failed += f
    p, f = test_model_mix06(vec, out); passed += p; failed += f
    p, f = test_model_mix07(vec, out); passed += p; failed += f
    p, f = test_model_mix08(vec, out); passed += p; failed += f
    p, f = test_model_mix09(vec, out); passed += p; failed += f
    p, f = test_model_mix10(vec, out); passed += p; failed += f
    p, f = test_model_mix11(vec, out); passed += p; failed += f
    p, f = test_model_mix12(vec, out); passed += p; failed += f
    p, f = test_model_mix13(vec, out); passed += p; failed += f
    p, f = test_model_mix14(vec, out); passed += p; failed += f
    p, f = test_model_mix15(vec, out); passed += p; failed += f
    p, f = test_model_all_opt1(vec, out); passed += p; failed += f
    p, f = test_model_all_opt2(vec, out); passed += p; failed += f
    p, f = test_model_all_opt3(vec, out); passed += p; failed += f
    p, f = test_model_all_opt4(vec, out); passed += p; failed += f
    p, f = test_model_all_opt5(vec, out); passed += p; failed += f
    return passed, failed
