# Generated by generate_emit_runner.mjs. DO NOT EDIT.
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from generated import *
from specodec.msgpack_reader import MsgPackReader
from specodec.msgpack_writer import MsgPackWriter
from specodec.json_reader import JsonReader
from specodec.json_writer import JsonWriter
from specodec.gron_reader import GronReader
from specodec.gron_writer import GronWriter


def test_model_nest_inner(vec, out):
    passed = 0
    failed = 0
    codec = NestInnerCodec
    try:
        b = open(os.path.join(vec, "NestInner.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestInner.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestInner mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestInner.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestInner.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestInner json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestInner.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestInner.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestInner unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestInner.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestInner.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestInner gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_nest_coord(vec, out):
    passed = 0
    failed = 0
    codec = NestCoordCodec
    try:
        b = open(os.path.join(vec, "NestCoord.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestCoord.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestCoord mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestCoord.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestCoord.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestCoord json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestCoord.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestCoord.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestCoord unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestCoord.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestCoord.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestCoord gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_nest_id_val(vec, out):
    passed = 0
    failed = 0
    codec = NestIdValCodec
    try:
        b = open(os.path.join(vec, "NestIdVal.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestIdVal.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestIdVal mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestIdVal.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestIdVal.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestIdVal json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestIdVal.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestIdVal.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestIdVal unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestIdVal.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestIdVal.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestIdVal gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_nest_label(vec, out):
    passed = 0
    failed = 0
    codec = NestLabelCodec
    try:
        b = open(os.path.join(vec, "NestLabel.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestLabel.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestLabel mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestLabel.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestLabel.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestLabel json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestLabel.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestLabel.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestLabel unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestLabel.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestLabel.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestLabel gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_nest_money(vec, out):
    passed = 0
    failed = 0
    codec = NestMoneyCodec
    try:
        b = open(os.path.join(vec, "NestMoney.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestMoney.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestMoney mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestMoney.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestMoney.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestMoney json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestMoney.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestMoney.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestMoney unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestMoney.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestMoney.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestMoney gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_nest_range32(vec, out):
    passed = 0
    failed = 0
    codec = NestRange32Codec
    try:
        b = open(os.path.join(vec, "NestRange32.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestRange32.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestRange32 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestRange32.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestRange32.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestRange32 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestRange32.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestRange32.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestRange32 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestRange32.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestRange32.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestRange32 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_nest_addr(vec, out):
    passed = 0
    failed = 0
    codec = NestAddrCodec
    try:
        b = open(os.path.join(vec, "NestAddr.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestAddr.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestAddr mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestAddr.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestAddr.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestAddr json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestAddr.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestAddr.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestAddr unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestAddr.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestAddr.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestAddr gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_nest_point3(vec, out):
    passed = 0
    failed = 0
    codec = NestPoint3Codec
    try:
        b = open(os.path.join(vec, "NestPoint3.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestPoint3.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestPoint3 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestPoint3.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestPoint3.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestPoint3 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestPoint3.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestPoint3.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestPoint3 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "NestPoint3.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "NestPoint3.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL NestPoint3 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_nest_inner(vec, out):
    passed = 0
    failed = 0
    codec = OptNestInnerCodec
    try:
        b = open(os.path.join(vec, "OptNestInner.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestInner.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestInner mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestInner.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestInner.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestInner json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestInner.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestInner.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestInner unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestInner.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestInner.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestInner gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_nest_coord(vec, out):
    passed = 0
    failed = 0
    codec = OptNestCoordCodec
    try:
        b = open(os.path.join(vec, "OptNestCoord.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestCoord.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestCoord mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestCoord.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestCoord.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestCoord json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestCoord.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestCoord.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestCoord unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestCoord.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestCoord.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestCoord gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_nest_id_val(vec, out):
    passed = 0
    failed = 0
    codec = OptNestIdValCodec
    try:
        b = open(os.path.join(vec, "OptNestIdVal.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestIdVal.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestIdVal mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestIdVal.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestIdVal.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestIdVal json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestIdVal.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestIdVal.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestIdVal unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestIdVal.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestIdVal.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestIdVal gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_nest_label(vec, out):
    passed = 0
    failed = 0
    codec = OptNestLabelCodec
    try:
        b = open(os.path.join(vec, "OptNestLabel.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestLabel.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestLabel mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestLabel.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestLabel.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestLabel json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestLabel.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestLabel.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestLabel unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestLabel.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestLabel.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestLabel gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_nest_money(vec, out):
    passed = 0
    failed = 0
    codec = OptNestMoneyCodec
    try:
        b = open(os.path.join(vec, "OptNestMoney.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestMoney.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestMoney mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestMoney.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestMoney.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestMoney json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestMoney.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestMoney.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestMoney unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestMoney.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestMoney.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestMoney gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_nest_range32(vec, out):
    passed = 0
    failed = 0
    codec = OptNestRange32Codec
    try:
        b = open(os.path.join(vec, "OptNestRange32.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestRange32.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestRange32 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestRange32.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestRange32.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestRange32 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestRange32.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestRange32.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestRange32 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestRange32.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestRange32.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestRange32 gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_nest_addr(vec, out):
    passed = 0
    failed = 0
    codec = OptNestAddrCodec
    try:
        b = open(os.path.join(vec, "OptNestAddr.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestAddr.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestAddr mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestAddr.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestAddr.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestAddr json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestAddr.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestAddr.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestAddr unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestAddr.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestAddr.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestAddr gron: " + str(e))
        failed += 1
    return passed, failed

def test_model_opt_nest_point3(vec, out):
    passed = 0
    failed = 0
    codec = OptNestPoint3Codec
    try:
        b = open(os.path.join(vec, "OptNestPoint3.msgpack"), "rb").read()
        obj = codec.decode(MsgPackReader(b))
        w = MsgPackWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestPoint3.msgpack"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestPoint3 mp: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestPoint3.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestPoint3.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestPoint3 json: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestPoint3.unformatted.json"), "rb").read()
        obj = codec.decode(JsonReader(b))
        w = JsonWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestPoint3.unformatted.json"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestPoint3 unformatted: " + str(e))
        failed += 1
    try:
        b = open(os.path.join(vec, "OptNestPoint3.gron"), "rb").read()
        obj = codec.decode(GronReader(b))
        w = GronWriter()
        codec.encode(w, obj)
        open(os.path.join(out, "OptNestPoint3.gron"), "wb").write(w.to_bytes())
        passed += 1
    except Exception as e:
        print("FAIL OptNestPoint3 gron: " + str(e))
        failed += 1
    return passed, failed
def run_AllTypes_Nests():
    passed = 0
    failed = 0
    vec = os.environ["VEC_DIR"]
    out = os.environ["OUT_DIR"]
    os.makedirs(out, exist_ok=True)

    # Object tests
    p, f = test_model_nest_inner(vec, out); passed += p; failed += f
    p, f = test_model_nest_coord(vec, out); passed += p; failed += f
    p, f = test_model_nest_id_val(vec, out); passed += p; failed += f
    p, f = test_model_nest_label(vec, out); passed += p; failed += f
    p, f = test_model_nest_money(vec, out); passed += p; failed += f
    p, f = test_model_nest_range32(vec, out); passed += p; failed += f
    p, f = test_model_nest_addr(vec, out); passed += p; failed += f
    p, f = test_model_nest_point3(vec, out); passed += p; failed += f
    p, f = test_model_opt_nest_inner(vec, out); passed += p; failed += f
    p, f = test_model_opt_nest_coord(vec, out); passed += p; failed += f
    p, f = test_model_opt_nest_id_val(vec, out); passed += p; failed += f
    p, f = test_model_opt_nest_label(vec, out); passed += p; failed += f
    p, f = test_model_opt_nest_money(vec, out); passed += p; failed += f
    p, f = test_model_opt_nest_range32(vec, out); passed += p; failed += f
    p, f = test_model_opt_nest_addr(vec, out); passed += p; failed += f
    p, f = test_model_opt_nest_point3(vec, out); passed += p; failed += f
    return passed, failed
