from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class SpecReader(Protocol):
    def begin_object(self) -> None: ...
    def has_next_field(self) -> bool: ...
    def read_field_name(self) -> str: ...
    def end_object(self) -> None: ...
    def begin_array(self) -> None: ...
    def has_next_element(self) -> bool: ...
    def end_array(self) -> None: ...
    def read_string(self) -> str: ...
    def read_bool(self) -> bool: ...
    def read_int32(self) -> int: ...
    def read_int64(self) -> int: ...
    def read_uint32(self) -> int: ...
    def read_uint64(self) -> int: ...
    def read_float32(self) -> float: ...
    def read_float64(self) -> float: ...
    def read_null(self) -> None: ...
    def read_bytes(self) -> bytes: ...
    def read_enum(self) -> str: ...
    def is_null(self) -> bool: ...
    def skip(self) -> None: ...
