from __future__ import annotations
from abc import ABC, abstractmethod


class SpecWriter(ABC):
    @abstractmethod
    def write_string(self, value: str) -> None: ...
    @abstractmethod
    def write_bool(self, value: bool) -> None: ...
    @abstractmethod
    def write_int32(self, value: int) -> None: ...
    @abstractmethod
    def write_int64(self, value: int) -> None: ...
    @abstractmethod
    def write_uint32(self, value: int) -> None: ...
    @abstractmethod
    def write_uint64(self, value: int) -> None: ...
    @abstractmethod
    def write_float32(self, value: float) -> None: ...
    @abstractmethod
    def write_float64(self, value: float) -> None: ...
    @abstractmethod
    def write_null(self) -> None: ...
    @abstractmethod
    def write_bytes(self, value: bytes) -> None: ...
    @abstractmethod
    def write_enum(self, value: str) -> None: ...
    @abstractmethod
    def begin_object(self, field_count: int) -> None: ...
    @abstractmethod
    def write_field(self, name: str) -> None: ...
    @abstractmethod
    def end_object(self) -> None: ...
    @abstractmethod
    def begin_array(self, element_count: int) -> None: ...
    @abstractmethod
    def next_element(self) -> None: ...
    @abstractmethod
    def end_array(self) -> None: ...
    @abstractmethod
    def to_bytes(self) -> bytes: ...
