# Generated by @specodec/typespec-emitter-python. DO NOT EDIT.
from __future__ import annotations
from dataclasses import dataclass
from typing import Optional, Any, Callable, List, TypeVar
from specodec import SpecWriter, SpecReader, SpecCodec

T = TypeVar('T')

@dataclass
class Foo:
    x: int

def write_foo(w: SpecWriter, obj: Foo) -> None:
    w.begin_object(1)
    w.write_field("x")
    w.write_int32(int(obj.x))
    w.end_object()

def decode_foo(r: SpecReader) -> Foo:
    kw: dict = {}
    r.begin_object()
    while r.has_next_field():
        key = r.read_field_name()
        if key == "x": kw["x"] = r.read_int32(); continue
        r.skip()
    r.end_object()
    return Foo(**kw)

FooCodec: SpecCodec = SpecCodec(
    encode=write_foo,
    decode=decode_foo,
)
