# Generated by @specodec/typespec-emitter-python. DO NOT EDIT.
from __future__ import annotations
from dataclasses import dataclass
from typing import Optional, Any, Callable, List, TypeVar
from specodec import SpecWriter, SpecReader, SpecCodec

T = TypeVar('T')

@dataclass
class Baz:
    z: float

def write_baz(w: SpecWriter, obj: Baz) -> None:
    w.begin_object(1)
    w.write_field("z")
    w.write_float64(float(obj.z))
    w.end_object()

def decode_baz(r: SpecReader) -> Baz:
    kw: dict = {}
    r.begin_object()
    while r.has_next_field():
        key = r.read_field_name()
        if key == "z": kw["z"] = r.read_float64(); continue
        r.skip()
    r.end_object()
    return Baz(**kw)

BazCodec: SpecCodec = SpecCodec(
    encode=write_baz,
    decode=decode_baz,
)
