# Generated by @specodec/typespec-emitter-python. DO NOT EDIT.
from __future__ import annotations
from dataclasses import dataclass
from typing import Optional, Any, Callable, List, TypeVar
from specodec import SpecWriter, SpecReader, SpecCodec

T = TypeVar('T')

@dataclass
class Bar:
    y: str

def write_bar(w: SpecWriter, obj: Bar) -> None:
    w.begin_object(1)
    w.write_field("y")
    w.write_string(obj.y)
    w.end_object()

def decode_bar(r: SpecReader) -> Bar:
    kw: dict = {}
    r.begin_object()
    while r.has_next_field():
        key = r.read_field_name()
        if key == "y": kw["y"] = r.read_string(); continue
        r.skip()
    r.end_object()
    return Bar(**kw)

BarCodec: SpecCodec = SpecCodec(
    encode=write_bar,
    decode=decode_bar,
)
