FROM dhi.io/python:3-alpine3.23-dev AS runner
WORKDIR /app
ARG HTTP_PROXY HTTPS_PROXY http_proxy https_proxy ALL_PROXY all_proxy
ENV http_proxy=${HTTP_PROXY} https_proxy=${HTTPS_PROXY} HTTP_PROXY=${HTTP_PROXY} HTTPS_PROXY=${HTTPS_PROXY} ALL_PROXY=${ALL_PROXY}
COPY --from=run run_py.py ./
COPY --from=specodec-runtime-python src/ /specodec-python/src/
COPY --from=vectors . /app/vectors/
COPY --from=output_ts . /app/output_ts/
RUN mkdir -p /app/output_py/scalars
ENV PYTHONPATH=/specodec-python/src
RUN python3 run_py.py