import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dir = path.dirname(fileURLToPath(import.meta.url));
const VEC_DIR = process.env.VEC_DIR || path.join(__dir, ".tests-cache", "vectors");

const manifestPath = path.join(VEC_DIR, "manifest.json");
const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf-8"));

const models = manifest.testModels;
const scalars = manifest.scalars;

function getReadMethod(type) {
  const map = {
    "int32": "read_int32",
    "int64": "read_int64",
    "uint32": "read_uint32",
    "uint64": "read_uint64",
    "float32": "read_float32",
    "float64": "read_float64",
    "string": "read_string",
    "bytes": "read_bytes",
    "bool": "read_bool",
  };
  return map[type] || "read_int32";
}

function getWriteMethod(type) {
  const map = {
    "int32": "write_int32",
    "int64": "write_int64",
    "uint32": "write_uint32",
    "uint64": "write_uint64",
    "float32": "write_float32",
    "float64": "write_float64",
    "string": "write_string",
    "bytes": "write_bytes",
    "bool": "write_bool",
  };
  return map[type] || "write_int32";
}

const code = `# Generated by generate_emit_runner.mjs. DO NOT EDIT.
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "generated"))

from all_types_types import *
from specodec.msgpack_reader import MsgPackReader
from specodec.msgpack_writer import MsgPackWriter
from specodec.json_reader import JsonReader
from specodec.json_writer import JsonWriter
from specodec.gron_reader import GronReader
from specodec.gron_writer import GronWriter

VEC = os.environ["VEC_DIR"]
OUT = os.environ["OUT_DIR"]
os.makedirs(OUT, exist_ok=True)
os.makedirs(os.path.join(OUT, "scalars"), exist_ok=True)

passed = 0
failed = 0

# Scalar tests
${Object.entries(scalars).map(([name, info]) => `
try:
    b = open(os.path.join(VEC, "scalars/${name}.mp"), "rb").read()
    r = MsgPackReader(b)
    val = r.${getReadMethod(info.type)}()
    w = MsgPackWriter()
    w.${getWriteMethod(info.type)}(val)
    open(os.path.join(OUT, "scalars/${name}.mp"), "wb").write(w.to_bytes())
    passed += 1
except Exception as e:
    print("FAIL ${name} mp: " + str(e))
    failed += 1
`).join("")}

# Object tests
${models.map(m => `
try:
    b = open(os.path.join(VEC, "${m}.msgpack"), "rb").read()
    codec = ${m}Codec
    obj = codec.decode(MsgPackReader(b))
    w = MsgPackWriter()
    codec.encode(w, obj)
    open(os.path.join(OUT, "${m}.msgpack"), "wb").write(w.to_bytes())
    passed += 1
except Exception as e:
    print("FAIL ${m} mp: " + str(e))
    failed += 1

try:
    b = open(os.path.join(VEC, "${m}.json"), "rb").read()
    codec = ${m}Codec
    obj = codec.decode(JsonReader(b))
    w = JsonWriter()
    codec.encode(w, obj)
    open(os.path.join(OUT, "${m}.json"), "wb").write(w.to_bytes())
    passed += 1
except Exception as e:
    print("FAIL ${m} json: " + str(e))
    failed += 1

try:
    b = open(os.path.join(VEC, "${m}.unformatted.json"), "rb").read()
    codec = ${m}Codec
    obj = codec.decode(JsonReader(b))
    w = JsonWriter()
    codec.encode(w, obj)
    open(os.path.join(OUT, "${m}.unformatted.json"), "wb").write(w.to_bytes())
    passed += 1
except Exception as e:
    print("FAIL ${m} unformatted: " + str(e))
    failed += 1

try:
    b = open(os.path.join(VEC, "${m}.gron"), "rb").read()
    codec = ${m}Codec
    obj = codec.decode(GronReader(b))
    w = GronWriter()
    codec.encode(w, obj)
    open(os.path.join(OUT, "${m}.gron"), "wb").write(w.to_bytes())
    passed += 1
except Exception as e:
    print("FAIL ${m} gron: " + str(e))
    failed += 1
`).join("")}

print(f"emit-python: {passed} passed, {failed} failed")
if failed > 0:
    sys.exit(1)
`;

const outFile = path.join(__dir, "src", "run_emit.py");
fs.writeFileSync(outFile, code);
console.log("Generated src/run_emit.py with " + models.length + " models + " + Object.keys(scalars).length + " scalars");